// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/response/check-profile-by-account-id-response.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.response;

public final class CheckProfileByAccountIdResponseOuterClass {
  private CheckProfileByAccountIdResponseOuterClass() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor internal_static_response_CheckProfileByAccountIdResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_response_CheckProfileByAccountIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\nBaccount/v2/dto/response/check-profile-" +
            "by-account-id-response.proto\022\010response\"4" +
            "\n\037CheckProfileByAccountIdResponse\022\021\n\tis_" +
            "exists\030\001 \001(\010B \n\034grpc.account.v2.dto.resp" +
            "onseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_response_CheckProfileByAccountIdResponse_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_response_CheckProfileByAccountIdResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_CheckProfileByAccountIdResponse_descriptor,
        new java.lang.String[] { "IsExists", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
