// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/response/get-profile-by-account-id-response.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.response;

/**
 * Protobuf type {@code response.GetProfileByAccountIdResponse}
 */
public final class GetProfileByAccountIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:response.GetProfileByAccountIdResponse)
    GetProfileByAccountIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use GetProfileByAccountIdResponse.newBuilder() to construct.
  private GetProfileByAccountIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private GetProfileByAccountIdResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({ "unused" })
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetProfileByAccountIdResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.internal_static_response_GetProfileByAccountIdResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
    return grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.internal_static_response_GetProfileByAccountIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.account.v2.dto.response.GetProfileByAccountIdResponse.class,
            grpc.account.v2.dto.response.GetProfileByAccountIdResponse.Builder.class);
  }

  private int bitField0_;
  public static final int PROFILE_FIELD_NUMBER = 2;
  private grpc.account.v2.dto.response.ProfileResponse profile_;

  /**
   * <code>.response.ProfileResponse profile = 2;</code>
   * 
   * @return Whether the profile field is set.
   */
  @java.lang.Override
  public boolean hasProfile() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>.response.ProfileResponse profile = 2;</code>
   * 
   * @return The profile.
   */
  @java.lang.Override
  public grpc.account.v2.dto.response.ProfileResponse getProfile() {
    return profile_ == null ? grpc.account.v2.dto.response.ProfileResponse.getDefaultInstance() : profile_;
  }

  /**
   * <code>.response.ProfileResponse profile = 2;</code>
   */
  @java.lang.Override
  public grpc.account.v2.dto.response.ProfileResponseOrBuilder getProfileOrBuilder() {
    return profile_ == null ? grpc.account.v2.dto.response.ProfileResponse.getDefaultInstance() : profile_;
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getProfile());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getProfile());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof grpc.account.v2.dto.response.GetProfileByAccountIdResponse)) {
      return super.equals(obj);
    }
    grpc.account.v2.dto.response.GetProfileByAccountIdResponse other = (grpc.account.v2.dto.response.GetProfileByAccountIdResponse) obj;

    if (hasProfile() != other.hasProfile())
      return false;
    if (hasProfile()) {
      if (!getProfile()
          .equals(other.getProfile()))
        return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields()))
      return false;
    return true;
  }

  @SuppressWarnings("unchecked")
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProfile()) {
      hash = (37 * hash) + PROFILE_FIELD_NUMBER;
      hash = (53 * hash) + getProfile().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(grpc.account.v2.dto.response.GetProfileByAccountIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder()
        : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code response.GetProfileByAccountIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:response.GetProfileByAccountIdResponse)
      grpc.account.v2.dto.response.GetProfileByAccountIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.internal_static_response_GetProfileByAccountIdResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.internal_static_response_GetProfileByAccountIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.account.v2.dto.response.GetProfileByAccountIdResponse.class,
              grpc.account.v2.dto.response.GetProfileByAccountIdResponse.Builder.class);
    }

    // Construct using
    // grpc.account.v2.dto.response.GetProfileByAccountIdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getProfileFieldBuilder();
      }
    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      profile_ = null;
      if (profileBuilder_ != null) {
        profileBuilder_.dispose();
        profileBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.internal_static_response_GetProfileByAccountIdResponse_descriptor;
    }

    @java.lang.Override
    public grpc.account.v2.dto.response.GetProfileByAccountIdResponse getDefaultInstanceForType() {
      return grpc.account.v2.dto.response.GetProfileByAccountIdResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.account.v2.dto.response.GetProfileByAccountIdResponse build() {
      grpc.account.v2.dto.response.GetProfileByAccountIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.account.v2.dto.response.GetProfileByAccountIdResponse buildPartial() {
      grpc.account.v2.dto.response.GetProfileByAccountIdResponse result = new grpc.account.v2.dto.response.GetProfileByAccountIdResponse(
          this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.account.v2.dto.response.GetProfileByAccountIdResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.profile_ = profileBuilder_ == null
            ? profile_
            : profileBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.account.v2.dto.response.GetProfileByAccountIdResponse) {
        return mergeFrom((grpc.account.v2.dto.response.GetProfileByAccountIdResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.account.v2.dto.response.GetProfileByAccountIdResponse other) {
      if (other == grpc.account.v2.dto.response.GetProfileByAccountIdResponse.getDefaultInstance())
        return this;
      if (other.hasProfile()) {
        mergeProfile(other.getProfile());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              input.readMessage(
                  getProfileFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private grpc.account.v2.dto.response.ProfileResponse profile_;
    private com.google.protobuf.SingleFieldBuilderV3<grpc.account.v2.dto.response.ProfileResponse, grpc.account.v2.dto.response.ProfileResponse.Builder, grpc.account.v2.dto.response.ProfileResponseOrBuilder> profileBuilder_;

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     * 
     * @return Whether the profile field is set.
     */
    public boolean hasProfile() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     * 
     * @return The profile.
     */
    public grpc.account.v2.dto.response.ProfileResponse getProfile() {
      if (profileBuilder_ == null) {
        return profile_ == null ? grpc.account.v2.dto.response.ProfileResponse.getDefaultInstance() : profile_;
      } else {
        return profileBuilder_.getMessage();
      }
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    public Builder setProfile(grpc.account.v2.dto.response.ProfileResponse value) {
      if (profileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        profile_ = value;
      } else {
        profileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    public Builder setProfile(
        grpc.account.v2.dto.response.ProfileResponse.Builder builderForValue) {
      if (profileBuilder_ == null) {
        profile_ = builderForValue.build();
      } else {
        profileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    public Builder mergeProfile(grpc.account.v2.dto.response.ProfileResponse value) {
      if (profileBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
            profile_ != null &&
            profile_ != grpc.account.v2.dto.response.ProfileResponse.getDefaultInstance()) {
          getProfileBuilder().mergeFrom(value);
        } else {
          profile_ = value;
        }
      } else {
        profileBuilder_.mergeFrom(value);
      }
      if (profile_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    public Builder clearProfile() {
      bitField0_ = (bitField0_ & ~0x00000001);
      profile_ = null;
      if (profileBuilder_ != null) {
        profileBuilder_.dispose();
        profileBuilder_ = null;
      }
      onChanged();
      return this;
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    public grpc.account.v2.dto.response.ProfileResponse.Builder getProfileBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getProfileFieldBuilder().getBuilder();
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    public grpc.account.v2.dto.response.ProfileResponseOrBuilder getProfileOrBuilder() {
      if (profileBuilder_ != null) {
        return profileBuilder_.getMessageOrBuilder();
      } else {
        return profile_ == null ? grpc.account.v2.dto.response.ProfileResponse.getDefaultInstance() : profile_;
      }
    }

    /**
     * <code>.response.ProfileResponse profile = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<grpc.account.v2.dto.response.ProfileResponse, grpc.account.v2.dto.response.ProfileResponse.Builder, grpc.account.v2.dto.response.ProfileResponseOrBuilder> getProfileFieldBuilder() {
      if (profileBuilder_ == null) {
        profileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<grpc.account.v2.dto.response.ProfileResponse, grpc.account.v2.dto.response.ProfileResponse.Builder, grpc.account.v2.dto.response.ProfileResponseOrBuilder>(
            getProfile(),
            getParentForChildren(),
            isClean());
        profile_ = null;
      }
      return profileBuilder_;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:response.GetProfileByAccountIdResponse)
  }

  // @@protoc_insertion_point(class_scope:response.GetProfileByAccountIdResponse)
  private static final grpc.account.v2.dto.response.GetProfileByAccountIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.account.v2.dto.response.GetProfileByAccountIdResponse();
  }

  public static grpc.account.v2.dto.response.GetProfileByAccountIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetProfileByAccountIdResponse> PARSER = new com.google.protobuf.AbstractParser<GetProfileByAccountIdResponse>() {
    @java.lang.Override
    public GetProfileByAccountIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetProfileByAccountIdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetProfileByAccountIdResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.account.v2.dto.response.GetProfileByAccountIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
