// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking/booking-service.proto

// Protobuf Java Version: 3.25.1
package grpc.booking;

/**
 * Protobuf type {@code booking.UpdateBookingAfterPaymentRequest}
 */
public final class UpdateBookingAfterPaymentRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:booking.UpdateBookingAfterPaymentRequest)
    UpdateBookingAfterPaymentRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UpdateBookingAfterPaymentRequest.newBuilder() to construct.
  private UpdateBookingAfterPaymentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UpdateBookingAfterPaymentRequest() {
    paymentMethod_ = 0;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new UpdateBookingAfterPaymentRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BookingServiceOuterClass.internal_static_booking_UpdateBookingAfterPaymentRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BookingServiceOuterClass.internal_static_booking_UpdateBookingAfterPaymentRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            UpdateBookingAfterPaymentRequest.class, Builder.class);
  }

  public static final int BOOKING_ID_FIELD_NUMBER = 1;
  private int bookingId_ = 0;
  /**
   * <code>int32 booking_id = 1;</code>
   * @return The bookingId.
   */
  @Override
  public int getBookingId() {
    return bookingId_;
  }

  public static final int PAYMENT_METHOD_FIELD_NUMBER = 2;
  private int paymentMethod_ = 0;
  /**
   * <code>.constants.PaymentMethod payment_method = 2;</code>
   * @return The enum numeric value on the wire for paymentMethod.
   */
  @Override public int getPaymentMethodValue() {
    return paymentMethod_;
  }
  /**
   * <code>.constants.PaymentMethod payment_method = 2;</code>
   * @return The paymentMethod.
   */
  @Override public grpc.booking.constants.PaymentMethod getPaymentMethod() {
    grpc.booking.constants.PaymentMethod result = grpc.booking.constants.PaymentMethod.forNumber(paymentMethod_);
    return result == null ? grpc.booking.constants.PaymentMethod.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bookingId_ != 0) {
      output.writeInt32(1, bookingId_);
    }
    if (paymentMethod_ != grpc.booking.constants.PaymentMethod.VNPAY.getNumber()) {
      output.writeEnum(2, paymentMethod_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bookingId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, bookingId_);
    }
    if (paymentMethod_ != grpc.booking.constants.PaymentMethod.VNPAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, paymentMethod_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof UpdateBookingAfterPaymentRequest)) {
      return super.equals(obj);
    }
    UpdateBookingAfterPaymentRequest other = (UpdateBookingAfterPaymentRequest) obj;

    if (getBookingId()
        != other.getBookingId()) return false;
    if (paymentMethod_ != other.paymentMethod_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKING_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBookingId();
    hash = (37 * hash) + PAYMENT_METHOD_FIELD_NUMBER;
    hash = (53 * hash) + paymentMethod_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static UpdateBookingAfterPaymentRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static UpdateBookingAfterPaymentRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static UpdateBookingAfterPaymentRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static UpdateBookingAfterPaymentRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(UpdateBookingAfterPaymentRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code booking.UpdateBookingAfterPaymentRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:booking.UpdateBookingAfterPaymentRequest)
      UpdateBookingAfterPaymentRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BookingServiceOuterClass.internal_static_booking_UpdateBookingAfterPaymentRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BookingServiceOuterClass.internal_static_booking_UpdateBookingAfterPaymentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UpdateBookingAfterPaymentRequest.class, Builder.class);
    }

    // Construct using grpc.booking.UpdateBookingAfterPaymentRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bookingId_ = 0;
      paymentMethod_ = 0;
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BookingServiceOuterClass.internal_static_booking_UpdateBookingAfterPaymentRequest_descriptor;
    }

    @Override
    public UpdateBookingAfterPaymentRequest getDefaultInstanceForType() {
      return UpdateBookingAfterPaymentRequest.getDefaultInstance();
    }

    @Override
    public UpdateBookingAfterPaymentRequest build() {
      UpdateBookingAfterPaymentRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public UpdateBookingAfterPaymentRequest buildPartial() {
      UpdateBookingAfterPaymentRequest result = new UpdateBookingAfterPaymentRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(UpdateBookingAfterPaymentRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bookingId_ = bookingId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.paymentMethod_ = paymentMethod_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof UpdateBookingAfterPaymentRequest) {
        return mergeFrom((UpdateBookingAfterPaymentRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(UpdateBookingAfterPaymentRequest other) {
      if (other == UpdateBookingAfterPaymentRequest.getDefaultInstance()) return this;
      if (other.getBookingId() != 0) {
        setBookingId(other.getBookingId());
      }
      if (other.paymentMethod_ != 0) {
        setPaymentMethodValue(other.getPaymentMethodValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bookingId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              paymentMethod_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int bookingId_ ;
    /**
     * <code>int32 booking_id = 1;</code>
     * @return The bookingId.
     */
    @Override
    public int getBookingId() {
      return bookingId_;
    }
    /**
     * <code>int32 booking_id = 1;</code>
     * @param value The bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingId(int value) {

      bookingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 booking_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookingId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bookingId_ = 0;
      onChanged();
      return this;
    }

    private int paymentMethod_ = 0;
    /**
     * <code>.constants.PaymentMethod payment_method = 2;</code>
     * @return The enum numeric value on the wire for paymentMethod.
     */
    @Override public int getPaymentMethodValue() {
      return paymentMethod_;
    }
    /**
     * <code>.constants.PaymentMethod payment_method = 2;</code>
     * @param value The enum numeric value on the wire for paymentMethod to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentMethodValue(int value) {
      paymentMethod_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.constants.PaymentMethod payment_method = 2;</code>
     * @return The paymentMethod.
     */
    @Override
    public grpc.booking.constants.PaymentMethod getPaymentMethod() {
      grpc.booking.constants.PaymentMethod result = grpc.booking.constants.PaymentMethod.forNumber(paymentMethod_);
      return result == null ? grpc.booking.constants.PaymentMethod.UNRECOGNIZED : result;
    }
    /**
     * <code>.constants.PaymentMethod payment_method = 2;</code>
     * @param value The paymentMethod to set.
     * @return This builder for chaining.
     */
    public Builder setPaymentMethod(grpc.booking.constants.PaymentMethod value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000002;
      paymentMethod_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.constants.PaymentMethod payment_method = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaymentMethod() {
      bitField0_ = (bitField0_ & ~0x00000002);
      paymentMethod_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:booking.UpdateBookingAfterPaymentRequest)
  }

  // @@protoc_insertion_point(class_scope:booking.UpdateBookingAfterPaymentRequest)
  private static final UpdateBookingAfterPaymentRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new UpdateBookingAfterPaymentRequest();
  }

  public static UpdateBookingAfterPaymentRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UpdateBookingAfterPaymentRequest>
      PARSER = new com.google.protobuf.AbstractParser<UpdateBookingAfterPaymentRequest>() {
    @Override
    public UpdateBookingAfterPaymentRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UpdateBookingAfterPaymentRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<UpdateBookingAfterPaymentRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public UpdateBookingAfterPaymentRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

