# ---------------
# Custom config
# ---------------
bk-travel:
  config:
    database:
      server:
        url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bk_travel_auth}
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
# ---------------
# Other config
# ---------------
server:
  port: 8081
spring:
  application:
    name: auth-service
  liquibase:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bk_travel_auth}
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: gr1projectmailhust@gmail.com
    password: xutx mohn zokw nylp
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  server:
    hostname: discovery-server
    port: 8761
  instance:
#    prefer-ip-address: true
#    hostname: auth-service
    appname: auth-service
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka
auth:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: aresky_sercret_ast5ld3mdkisbaoyqmtnx7casdkycgajgf334twi5y35_124qwirweaser234
    expiration: 86400000
kafka:
  bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
  consumer:
    auto-offset-reset: latest
    group-id: auth-service-group
    client-id: auth-service-consumer