# ---------------
# Custom config
# ---------------
bk-travel:
  config:
    database:
      server:
        url: r2dbc:mysql://mysql-server:3306/bk_travel_auth
        username: root
        password: root
# ---------------
# Other config
# ---------------
server:
  port: 8081
spring:
  application:
    name: auth-service
  liquibase:
    url: jdbc:mysql://mysql-server:3306/bk_travel_auth
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  server:
    hostname: discovery-server
    port: 8761
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka
springdoc:
  packages-to-scan: com.aresky.authservice.controller
  swagger-ui:
    enabled: true
    path: "/swagger-ui.auth.html"
  api-docs:
    path: /api-docs
auth:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: aresky_sercret_ast5ld3mdkisbaoyqmtnx7casdkycgajgf334twi5y35_124qwirweaser234
    expiration: 86400000
#kafka:
#  bootstrap-servers:
#    url: http://localhost:9092
#  consumer:
#    auto-offset-reset: latest
#    group-id: bk-travel-group
