server:
  port: 8081
spring:
  application:
    name: auth-service
  r2dbc:
    url: r2dbc:mysql://${mysql-server.hostname}:${mysql-server.port}/bk_travel_auth?serverTimeZone=UTC
    username: root
    password: root
  liquibase:
    enabled: true
    url: jdbc:mysql://${mysql-server.hostname}:${mysql-server.port}/bk_travel_auth?serverTimeZone=UTC
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  server:
    hostname: discovery-server
    port: 8761
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka
springdoc:
  packages-to-scan: com.aresky.authservice.controller
  swagger-ui:
    enabled: true
    path: "/swagger-ui.html"
  api-docs:
    path: /api-docs
auth:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: aresky_sercret_ast5ld3mdkisbaoyqmtnx7casdkycgajgf334twi5y35_124qwirweaser234
    expiration: 86400000
mysql-server:
  hostname: mysql-server
  port: 3306
kafka:
  bootstrap-servers:
    url: http://localhost:9092
  consumer:
    auto-offset-reset: latest
    group-id: bk-travel-group
