# ---------------
# Custom config
# ---------------
bk-travel:
  config:
    database:
      server:
        url: r2dbc:mysql://mysql-server:3306/bk_travel_auth
        username: root
        password: root
# ---------------
# Other config
# ---------------
server:
  port: 8081
spring:
  application:
    name: auth-service
  liquibase:
    url: jdbc:mysql://mysql-server:3306/bk_travel_auth
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: gr1projectmailhust@gmail.com
    password: xutx mohn zokw nylp
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  server:
    hostname: discovery-server
    port: 8761
  instance:
    hostname: auth-service
    appname: auth-service
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka
auth:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: aresky_sercret_ast5ld3mdkisbaoyqmtnx7casdkycgajgf334twi5y35_124qwirweaser234
    expiration: 86400000
#kafka:
#  bootstrap-servers:
#    url: http://localhost:9092
#  consumer:
#    auto-offset-reset: latest
#    group-id: bk-travel-group
