// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staff/constants/staff_status.proto

// Protobuf Java Version: 3.25.1
package grpc.staff.constants.type;

/**
 * Protobuf enum {@code constants.StaffStatus}
 */
public enum StaffStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACTIVE = 0;</code>
   */
  ACTIVE(0),
  /**
   * <code>INACTIVE = 1;</code>
   */
  INACTIVE(1),
  /**
   * <code>ON_LEAVE = 2;</code>
   */
  ON_LEAVE(2),
  /**
   * <code>CONTRACT = 3;</code>
   */
  CONTRACT(3),
  /**
   * <code>TERMINATED = 4;</code>
   */
  TERMINATED(4),
  /**
   * <code>RETIRED = 5;</code>
   */
  RETIRED(5),
  /**
   * <code>PROBATION = 6;</code>
   */
  PROBATION(6),
  /**
   * <code>TRAINING = 7;</code>
   */
  TRAINING(7),
  /**
   * <code>SUSPENDED = 8;</code>
   */
  SUSPENDED(8),
  /**
   * <code>TRANSFERRED = 9;</code>
   */
  TRANSFERRED(9),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>ACTIVE = 0;</code>
   */
  public static final int ACTIVE_VALUE = 0;
  /**
   * <code>INACTIVE = 1;</code>
   */
  public static final int INACTIVE_VALUE = 1;
  /**
   * <code>ON_LEAVE = 2;</code>
   */
  public static final int ON_LEAVE_VALUE = 2;
  /**
   * <code>CONTRACT = 3;</code>
   */
  public static final int CONTRACT_VALUE = 3;
  /**
   * <code>TERMINATED = 4;</code>
   */
  public static final int TERMINATED_VALUE = 4;
  /**
   * <code>RETIRED = 5;</code>
   */
  public static final int RETIRED_VALUE = 5;
  /**
   * <code>PROBATION = 6;</code>
   */
  public static final int PROBATION_VALUE = 6;
  /**
   * <code>TRAINING = 7;</code>
   */
  public static final int TRAINING_VALUE = 7;
  /**
   * <code>SUSPENDED = 8;</code>
   */
  public static final int SUSPENDED_VALUE = 8;
  /**
   * <code>TRANSFERRED = 9;</code>
   */
  public static final int TRANSFERRED_VALUE = 9;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @Deprecated
  public static StaffStatus valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static StaffStatus forNumber(int value) {
    switch (value) {
      case 0: return ACTIVE;
      case 1: return INACTIVE;
      case 2: return ON_LEAVE;
      case 3: return CONTRACT;
      case 4: return TERMINATED;
      case 5: return RETIRED;
      case 6: return PROBATION;
      case 7: return TRAINING;
      case 8: return SUSPENDED;
      case 9: return TRANSFERRED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StaffStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StaffStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StaffStatus>() {
          public StaffStatus findValueByNumber(int number) {
            return StaffStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return StaffStatusOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final StaffStatus[] VALUES = values();

  public static StaffStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private StaffStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:constants.StaffStatus)
}

