// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour-service/tour-service.proto

// Protobuf Java Version: 3.25.1
package grpc.tour;

/**
 * Protobuf type {@code SubTourDetailsResponse}
 */
public final class SubTourDetailsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubTourDetailsResponse)
    SubTourDetailsResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use SubTourDetailsResponse.newBuilder() to construct.
  private SubTourDetailsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private SubTourDetailsResponse() {
    title_ = "";
    tourTitle_ = "";
    tourCode_ = "";
    image1_ = "";
    image2_ = "";
    image3_ = "";
    image4_ = "";
    destinations_ = "";
    duration_ = "";
    departureTime_ = "";
    departureLocation_ = "";
    schedules_ = "";
    vehicle_ = "";
    status_ = "";
    createdTime_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({ "unused" })
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SubTourDetailsResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return grpc.tour.TourServiceOuterClass.internal_static_SubTourDetailsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
    return grpc.tour.TourServiceOuterClass.internal_static_SubTourDetailsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.tour.SubTourDetailsResponse.class, grpc.tour.SubTourDetailsResponse.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;

  /**
   * <code>int32 id = 1;</code>
   * 
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int TOUR_ID_FIELD_NUMBER = 2;
  private int tourId_ = 0;

  /**
   * <code>int32 tour_id = 2;</code>
   * 
   * @return The tourId.
   */
  @java.lang.Override
  public int getTourId() {
    return tourId_;
  }

  public static final int TITLE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";

  /**
   * <code>string title = 3;</code>
   * 
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }

  /**
   * <code>string title = 3;</code>
   * 
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOUR_TITLE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tourTitle_ = "";

  /**
   * <code>string tour_title = 4;</code>
   * 
   * @return The tourTitle.
   */
  @java.lang.Override
  public java.lang.String getTourTitle() {
    java.lang.Object ref = tourTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tourTitle_ = s;
      return s;
    }
  }

  /**
   * <code>string tour_title = 4;</code>
   * 
   * @return The bytes for tourTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTourTitleBytes() {
    java.lang.Object ref = tourTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      tourTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOUR_CODE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tourCode_ = "";

  /**
   * <code>string tour_code = 5;</code>
   * 
   * @return The tourCode.
   */
  @java.lang.Override
  public java.lang.String getTourCode() {
    java.lang.Object ref = tourCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tourCode_ = s;
      return s;
    }
  }

  /**
   * <code>string tour_code = 5;</code>
   * 
   * @return The bytes for tourCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getTourCodeBytes() {
    java.lang.Object ref = tourCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      tourCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE1_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object image1_ = "";

  /**
   * <code>string image1 = 6;</code>
   * 
   * @return The image1.
   */
  @java.lang.Override
  public java.lang.String getImage1() {
    java.lang.Object ref = image1_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image1_ = s;
      return s;
    }
  }

  /**
   * <code>string image1 = 6;</code>
   * 
   * @return The bytes for image1.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImage1Bytes() {
    java.lang.Object ref = image1_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      image1_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE2_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile java.lang.Object image2_ = "";

  /**
   * <code>string image2 = 7;</code>
   * 
   * @return The image2.
   */
  @java.lang.Override
  public java.lang.String getImage2() {
    java.lang.Object ref = image2_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image2_ = s;
      return s;
    }
  }

  /**
   * <code>string image2 = 7;</code>
   * 
   * @return The bytes for image2.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImage2Bytes() {
    java.lang.Object ref = image2_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      image2_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE3_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object image3_ = "";

  /**
   * <code>string image3 = 8;</code>
   * 
   * @return The image3.
   */
  @java.lang.Override
  public java.lang.String getImage3() {
    java.lang.Object ref = image3_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image3_ = s;
      return s;
    }
  }

  /**
   * <code>string image3 = 8;</code>
   * 
   * @return The bytes for image3.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImage3Bytes() {
    java.lang.Object ref = image3_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      image3_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE4_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object image4_ = "";

  /**
   * <code>string image4 = 9;</code>
   * 
   * @return The image4.
   */
  @java.lang.Override
  public java.lang.String getImage4() {
    java.lang.Object ref = image4_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      image4_ = s;
      return s;
    }
  }

  /**
   * <code>string image4 = 9;</code>
   * 
   * @return The bytes for image4.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImage4Bytes() {
    java.lang.Object ref = image4_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      image4_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESTINATIONS_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private volatile java.lang.Object destinations_ = "";

  /**
   * <code>string destinations = 10;</code>
   * 
   * @return The destinations.
   */
  @java.lang.Override
  public java.lang.String getDestinations() {
    java.lang.Object ref = destinations_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      destinations_ = s;
      return s;
    }
  }

  /**
   * <code>string destinations = 10;</code>
   * 
   * @return The bytes for destinations.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDestinationsBytes() {
    java.lang.Object ref = destinations_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      destinations_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object duration_ = "";

  /**
   * <code>string duration = 11;</code>
   * 
   * @return The duration.
   */
  @java.lang.Override
  public java.lang.String getDuration() {
    java.lang.Object ref = duration_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      duration_ = s;
      return s;
    }
  }

  /**
   * <code>string duration = 11;</code>
   * 
   * @return The bytes for duration.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDurationBytes() {
    java.lang.Object ref = duration_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      duration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_TIME_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object departureTime_ = "";

  /**
   * <code>string departure_time = 12;</code>
   * 
   * @return The departureTime.
   */
  @java.lang.Override
  public java.lang.String getDepartureTime() {
    java.lang.Object ref = departureTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departureTime_ = s;
      return s;
    }
  }

  /**
   * <code>string departure_time = 12;</code>
   * 
   * @return The bytes for departureTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDepartureTimeBytes() {
    java.lang.Object ref = departureTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      departureTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_LOCATION_FIELD_NUMBER = 13;
  @SuppressWarnings("serial")
  private volatile java.lang.Object departureLocation_ = "";

  /**
   * <code>string departure_location = 13;</code>
   * 
   * @return The departureLocation.
   */
  @java.lang.Override
  public java.lang.String getDepartureLocation() {
    java.lang.Object ref = departureLocation_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      departureLocation_ = s;
      return s;
    }
  }

  /**
   * <code>string departure_location = 13;</code>
   * 
   * @return The bytes for departureLocation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDepartureLocationBytes() {
    java.lang.Object ref = departureLocation_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      departureLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCHEDULES_FIELD_NUMBER = 14;
  @SuppressWarnings("serial")
  private volatile java.lang.Object schedules_ = "";

  /**
   * <code>string schedules = 14;</code>
   * 
   * @return The schedules.
   */
  @java.lang.Override
  public java.lang.String getSchedules() {
    java.lang.Object ref = schedules_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      schedules_ = s;
      return s;
    }
  }

  /**
   * <code>string schedules = 14;</code>
   * 
   * @return The bytes for schedules.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSchedulesBytes() {
    java.lang.Object ref = schedules_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      schedules_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object vehicle_ = "";

  /**
   * <code>string vehicle = 15;</code>
   * 
   * @return The vehicle.
   */
  @java.lang.Override
  public java.lang.String getVehicle() {
    java.lang.Object ref = vehicle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      vehicle_ = s;
      return s;
    }
  }

  /**
   * <code>string vehicle = 15;</code>
   * 
   * @return The bytes for vehicle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getVehicleBytes() {
    java.lang.Object ref = vehicle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      vehicle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 16;
  @SuppressWarnings("serial")
  private volatile java.lang.Object status_ = "";

  /**
   * <code>string status = 16;</code>
   * 
   * @return The status.
   */
  @java.lang.Override
  public java.lang.String getStatus() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      status_ = s;
      return s;
    }
  }

  /**
   * <code>string status = 16;</code>
   * 
   * @return The bytes for status.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStatusBytes() {
    java.lang.Object ref = status_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      status_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_SEATS_FIELD_NUMBER = 17;
  private int totalSeats_ = 0;

  /**
   * <code>int32 total_seats = 17;</code>
   * 
   * @return The totalSeats.
   */
  @java.lang.Override
  public int getTotalSeats() {
    return totalSeats_;
  }

  public static final int AVAILABLE_SEATS_FIELD_NUMBER = 18;
  private int availableSeats_ = 0;

  /**
   * <code>int32 available_seats = 18;</code>
   * 
   * @return The availableSeats.
   */
  @java.lang.Override
  public int getAvailableSeats() {
    return availableSeats_;
  }

  public static final int ADULT_PRICE_FIELD_NUMBER = 19;
  private int adultPrice_ = 0;

  /**
   * <code>int32 adult_price = 19;</code>
   * 
   * @return The adultPrice.
   */
  @java.lang.Override
  public int getAdultPrice() {
    return adultPrice_;
  }

  public static final int CHILDREN_PRICE_FIELD_NUMBER = 20;
  private int childrenPrice_ = 0;

  /**
   * <code>int32 children_price = 20;</code>
   * 
   * @return The childrenPrice.
   */
  @java.lang.Override
  public int getChildrenPrice() {
    return childrenPrice_;
  }

  public static final int BABY_PRICE_FIELD_NUMBER = 21;
  private int babyPrice_ = 0;

  /**
   * <code>int32 baby_price = 21;</code>
   * 
   * @return The babyPrice.
   */
  @java.lang.Override
  public int getBabyPrice() {
    return babyPrice_;
  }

  public static final int TOUR_GUIDE_ID_FIELD_NUMBER = 22;
  private int tourGuideId_ = 0;

  /**
   * <code>int32 tour_guide_id = 22;</code>
   * 
   * @return The tourGuideId.
   */
  @java.lang.Override
  public int getTourGuideId() {
    return tourGuideId_;
  }

  public static final int CREATED_TIME_FIELD_NUMBER = 23;
  @SuppressWarnings("serial")
  private volatile java.lang.Object createdTime_ = "";

  /**
   * <code>string created_time = 23;</code>
   * 
   * @return The createdTime.
   */
  @java.lang.Override
  public java.lang.String getCreatedTime() {
    java.lang.Object ref = createdTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdTime_ = s;
      return s;
    }
  }

  /**
   * <code>string created_time = 23;</code>
   * 
   * @return The bytes for createdTime.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getCreatedTimeBytes() {
    java.lang.Object ref = createdTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (java.lang.String) ref);
      createdTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (tourId_ != 0) {
      output.writeInt32(2, tourId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tourTitle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tourTitle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tourCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, tourCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image1_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, image1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image2_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, image2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image3_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, image3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image4_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, image4_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinations_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, destinations_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(duration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, duration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, departureTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLocation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, departureLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schedules_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, schedules_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, vehicle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, status_);
    }
    if (totalSeats_ != 0) {
      output.writeInt32(17, totalSeats_);
    }
    if (availableSeats_ != 0) {
      output.writeInt32(18, availableSeats_);
    }
    if (adultPrice_ != 0) {
      output.writeInt32(19, adultPrice_);
    }
    if (childrenPrice_ != 0) {
      output.writeInt32(20, childrenPrice_);
    }
    if (babyPrice_ != 0) {
      output.writeInt32(21, babyPrice_);
    }
    if (tourGuideId_ != 0) {
      output.writeInt32(22, tourGuideId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 23, createdTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
    }
    if (tourId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tourId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tourTitle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tourTitle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tourCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, tourCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image1_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, image1_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image2_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, image2_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image3_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, image3_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(image4_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, image4_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destinations_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, destinations_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(duration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, duration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, departureTime_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLocation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, departureLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(schedules_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, schedules_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, vehicle_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(status_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, status_);
    }
    if (totalSeats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, totalSeats_);
    }
    if (availableSeats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(18, availableSeats_);
    }
    if (adultPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(19, adultPrice_);
    }
    if (childrenPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, childrenPrice_);
    }
    if (babyPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, babyPrice_);
    }
    if (tourGuideId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(22, tourGuideId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(23, createdTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof grpc.tour.SubTourDetailsResponse)) {
      return super.equals(obj);
    }
    grpc.tour.SubTourDetailsResponse other = (grpc.tour.SubTourDetailsResponse) obj;

    if (getId() != other.getId())
      return false;
    if (getTourId() != other.getTourId())
      return false;
    if (!getTitle()
        .equals(other.getTitle()))
      return false;
    if (!getTourTitle()
        .equals(other.getTourTitle()))
      return false;
    if (!getTourCode()
        .equals(other.getTourCode()))
      return false;
    if (!getImage1()
        .equals(other.getImage1()))
      return false;
    if (!getImage2()
        .equals(other.getImage2()))
      return false;
    if (!getImage3()
        .equals(other.getImage3()))
      return false;
    if (!getImage4()
        .equals(other.getImage4()))
      return false;
    if (!getDestinations()
        .equals(other.getDestinations()))
      return false;
    if (!getDuration()
        .equals(other.getDuration()))
      return false;
    if (!getDepartureTime()
        .equals(other.getDepartureTime()))
      return false;
    if (!getDepartureLocation()
        .equals(other.getDepartureLocation()))
      return false;
    if (!getSchedules()
        .equals(other.getSchedules()))
      return false;
    if (!getVehicle()
        .equals(other.getVehicle()))
      return false;
    if (!getStatus()
        .equals(other.getStatus()))
      return false;
    if (getTotalSeats() != other.getTotalSeats())
      return false;
    if (getAvailableSeats() != other.getAvailableSeats())
      return false;
    if (getAdultPrice() != other.getAdultPrice())
      return false;
    if (getChildrenPrice() != other.getChildrenPrice())
      return false;
    if (getBabyPrice() != other.getBabyPrice())
      return false;
    if (getTourGuideId() != other.getTourGuideId())
      return false;
    if (!getCreatedTime()
        .equals(other.getCreatedTime()))
      return false;
    if (!getUnknownFields().equals(other.getUnknownFields()))
      return false;
    return true;
  }

  @SuppressWarnings("unchecked")
  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TOUR_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTourId();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + TOUR_TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTourTitle().hashCode();
    hash = (37 * hash) + TOUR_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getTourCode().hashCode();
    hash = (37 * hash) + IMAGE1_FIELD_NUMBER;
    hash = (53 * hash) + getImage1().hashCode();
    hash = (37 * hash) + IMAGE2_FIELD_NUMBER;
    hash = (53 * hash) + getImage2().hashCode();
    hash = (37 * hash) + IMAGE3_FIELD_NUMBER;
    hash = (53 * hash) + getImage3().hashCode();
    hash = (37 * hash) + IMAGE4_FIELD_NUMBER;
    hash = (53 * hash) + getImage4().hashCode();
    hash = (37 * hash) + DESTINATIONS_FIELD_NUMBER;
    hash = (53 * hash) + getDestinations().hashCode();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDuration().hashCode();
    hash = (37 * hash) + DEPARTURE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureTime().hashCode();
    hash = (37 * hash) + DEPARTURE_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureLocation().hashCode();
    hash = (37 * hash) + SCHEDULES_FIELD_NUMBER;
    hash = (53 * hash) + getSchedules().hashCode();
    hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
    hash = (53 * hash) + getVehicle().hashCode();
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus().hashCode();
    hash = (37 * hash) + TOTAL_SEATS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSeats();
    hash = (37 * hash) + AVAILABLE_SEATS_FIELD_NUMBER;
    hash = (53 * hash) + getAvailableSeats();
    hash = (37 * hash) + ADULT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getAdultPrice();
    hash = (37 * hash) + CHILDREN_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getChildrenPrice();
    hash = (37 * hash) + BABY_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getBabyPrice();
    hash = (37 * hash) + TOUR_GUIDE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTourGuideId();
    hash = (37 * hash) + CREATED_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedTime().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tour.SubTourDetailsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static grpc.tour.SubTourDetailsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static grpc.tour.SubTourDetailsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(grpc.tour.SubTourDetailsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder()
        : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code SubTourDetailsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubTourDetailsResponse)
      grpc.tour.SubTourDetailsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return grpc.tour.TourServiceOuterClass.internal_static_SubTourDetailsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return grpc.tour.TourServiceOuterClass.internal_static_SubTourDetailsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.tour.SubTourDetailsResponse.class, grpc.tour.SubTourDetailsResponse.Builder.class);
    }

    // Construct using grpc.tour.SubTourDetailsResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }

    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      tourId_ = 0;
      title_ = "";
      tourTitle_ = "";
      tourCode_ = "";
      image1_ = "";
      image2_ = "";
      image3_ = "";
      image4_ = "";
      destinations_ = "";
      duration_ = "";
      departureTime_ = "";
      departureLocation_ = "";
      schedules_ = "";
      vehicle_ = "";
      status_ = "";
      totalSeats_ = 0;
      availableSeats_ = 0;
      adultPrice_ = 0;
      childrenPrice_ = 0;
      babyPrice_ = 0;
      tourGuideId_ = 0;
      createdTime_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return grpc.tour.TourServiceOuterClass.internal_static_SubTourDetailsResponse_descriptor;
    }

    @java.lang.Override
    public grpc.tour.SubTourDetailsResponse getDefaultInstanceForType() {
      return grpc.tour.SubTourDetailsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.tour.SubTourDetailsResponse build() {
      grpc.tour.SubTourDetailsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.tour.SubTourDetailsResponse buildPartial() {
      grpc.tour.SubTourDetailsResponse result = new grpc.tour.SubTourDetailsResponse(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(grpc.tour.SubTourDetailsResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tourId_ = tourId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.tourTitle_ = tourTitle_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.tourCode_ = tourCode_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.image1_ = image1_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.image2_ = image2_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.image3_ = image3_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.image4_ = image4_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.destinations_ = destinations_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.departureTime_ = departureTime_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.departureLocation_ = departureLocation_;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.schedules_ = schedules_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.vehicle_ = vehicle_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.status_ = status_;
      }
      if (((from_bitField0_ & 0x00010000) != 0)) {
        result.totalSeats_ = totalSeats_;
      }
      if (((from_bitField0_ & 0x00020000) != 0)) {
        result.availableSeats_ = availableSeats_;
      }
      if (((from_bitField0_ & 0x00040000) != 0)) {
        result.adultPrice_ = adultPrice_;
      }
      if (((from_bitField0_ & 0x00080000) != 0)) {
        result.childrenPrice_ = childrenPrice_;
      }
      if (((from_bitField0_ & 0x00100000) != 0)) {
        result.babyPrice_ = babyPrice_;
      }
      if (((from_bitField0_ & 0x00200000) != 0)) {
        result.tourGuideId_ = tourGuideId_;
      }
      if (((from_bitField0_ & 0x00400000) != 0)) {
        result.createdTime_ = createdTime_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }

    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }

    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.tour.SubTourDetailsResponse) {
        return mergeFrom((grpc.tour.SubTourDetailsResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.tour.SubTourDetailsResponse other) {
      if (other == grpc.tour.SubTourDetailsResponse.getDefaultInstance())
        return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.getTourId() != 0) {
        setTourId(other.getTourId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getTourTitle().isEmpty()) {
        tourTitle_ = other.tourTitle_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getTourCode().isEmpty()) {
        tourCode_ = other.tourCode_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getImage1().isEmpty()) {
        image1_ = other.image1_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getImage2().isEmpty()) {
        image2_ = other.image2_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getImage3().isEmpty()) {
        image3_ = other.image3_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getImage4().isEmpty()) {
        image4_ = other.image4_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (!other.getDestinations().isEmpty()) {
        destinations_ = other.destinations_;
        bitField0_ |= 0x00000200;
        onChanged();
      }
      if (!other.getDuration().isEmpty()) {
        duration_ = other.duration_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (!other.getDepartureTime().isEmpty()) {
        departureTime_ = other.departureTime_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (!other.getDepartureLocation().isEmpty()) {
        departureLocation_ = other.departureLocation_;
        bitField0_ |= 0x00001000;
        onChanged();
      }
      if (!other.getSchedules().isEmpty()) {
        schedules_ = other.schedules_;
        bitField0_ |= 0x00002000;
        onChanged();
      }
      if (!other.getVehicle().isEmpty()) {
        vehicle_ = other.vehicle_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (!other.getStatus().isEmpty()) {
        status_ = other.status_;
        bitField0_ |= 0x00008000;
        onChanged();
      }
      if (other.getTotalSeats() != 0) {
        setTotalSeats(other.getTotalSeats());
      }
      if (other.getAvailableSeats() != 0) {
        setAvailableSeats(other.getAvailableSeats());
      }
      if (other.getAdultPrice() != 0) {
        setAdultPrice(other.getAdultPrice());
      }
      if (other.getChildrenPrice() != 0) {
        setChildrenPrice(other.getChildrenPrice());
      }
      if (other.getBabyPrice() != 0) {
        setBabyPrice(other.getBabyPrice());
      }
      if (other.getTourGuideId() != 0) {
        setTourGuideId(other.getTourGuideId());
      }
      if (!other.getCreatedTime().isEmpty()) {
        createdTime_ = other.createdTime_;
        bitField0_ |= 0x00400000;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              tourId_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              tourTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              tourCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              image1_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              image2_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              image3_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              image4_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              destinations_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000200;
              break;
            } // case 82
            case 90: {
              duration_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              departureTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              departureLocation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              schedules_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 122: {
              vehicle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 130: {
              status_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00008000;
              break;
            } // case 130
            case 136: {
              totalSeats_ = input.readInt32();
              bitField0_ |= 0x00010000;
              break;
            } // case 136
            case 144: {
              availableSeats_ = input.readInt32();
              bitField0_ |= 0x00020000;
              break;
            } // case 144
            case 152: {
              adultPrice_ = input.readInt32();
              bitField0_ |= 0x00040000;
              break;
            } // case 152
            case 160: {
              childrenPrice_ = input.readInt32();
              bitField0_ |= 0x00080000;
              break;
            } // case 160
            case 168: {
              babyPrice_ = input.readInt32();
              bitField0_ |= 0x00100000;
              break;
            } // case 168
            case 176: {
              tourGuideId_ = input.readInt32();
              bitField0_ |= 0x00200000;
              break;
            } // case 176
            case 186: {
              createdTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00400000;
              break;
            } // case 186
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private int id_;

    /**
     * <code>int32 id = 1;</code>
     * 
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    /**
     * <code>int32 id = 1;</code>
     * 
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>int32 id = 1;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private int tourId_;

    /**
     * <code>int32 tour_id = 2;</code>
     * 
     * @return The tourId.
     */
    @java.lang.Override
    public int getTourId() {
      return tourId_;
    }

    /**
     * <code>int32 tour_id = 2;</code>
     * 
     * @param value The tourId to set.
     * @return This builder for chaining.
     */
    public Builder setTourId(int value) {

      tourId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>int32 tour_id = 2;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTourId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tourId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";

    /**
     * <code>string title = 3;</code>
     * 
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string title = 3;</code>
     * 
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string title = 3;</code>
     * 
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /**
     * <code>string title = 3;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    /**
     * <code>string title = 3;</code>
     * 
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object tourTitle_ = "";

    /**
     * <code>string tour_title = 4;</code>
     * 
     * @return The tourTitle.
     */
    public java.lang.String getTourTitle() {
      java.lang.Object ref = tourTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tourTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string tour_title = 4;</code>
     * 
     * @return The bytes for tourTitle.
     */
    public com.google.protobuf.ByteString getTourTitleBytes() {
      java.lang.Object ref = tourTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        tourTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string tour_title = 4;</code>
     * 
     * @param value The tourTitle to set.
     * @return This builder for chaining.
     */
    public Builder setTourTitle(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      tourTitle_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     * <code>string tour_title = 4;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTourTitle() {
      tourTitle_ = getDefaultInstance().getTourTitle();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    /**
     * <code>string tour_title = 4;</code>
     * 
     * @param value The bytes for tourTitle to set.
     * @return This builder for chaining.
     */
    public Builder setTourTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      tourTitle_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object tourCode_ = "";

    /**
     * <code>string tour_code = 5;</code>
     * 
     * @return The tourCode.
     */
    public java.lang.String getTourCode() {
      java.lang.Object ref = tourCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tourCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string tour_code = 5;</code>
     * 
     * @return The bytes for tourCode.
     */
    public com.google.protobuf.ByteString getTourCodeBytes() {
      java.lang.Object ref = tourCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        tourCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string tour_code = 5;</code>
     * 
     * @param value The tourCode to set.
     * @return This builder for chaining.
     */
    public Builder setTourCode(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      tourCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    /**
     * <code>string tour_code = 5;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTourCode() {
      tourCode_ = getDefaultInstance().getTourCode();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    /**
     * <code>string tour_code = 5;</code>
     * 
     * @param value The bytes for tourCode to set.
     * @return This builder for chaining.
     */
    public Builder setTourCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      tourCode_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object image1_ = "";

    /**
     * <code>string image1 = 6;</code>
     * 
     * @return The image1.
     */
    public java.lang.String getImage1() {
      java.lang.Object ref = image1_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image1_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string image1 = 6;</code>
     * 
     * @return The bytes for image1.
     */
    public com.google.protobuf.ByteString getImage1Bytes() {
      java.lang.Object ref = image1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        image1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string image1 = 6;</code>
     * 
     * @param value The image1 to set.
     * @return This builder for chaining.
     */
    public Builder setImage1(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      image1_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    /**
     * <code>string image1 = 6;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearImage1() {
      image1_ = getDefaultInstance().getImage1();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }

    /**
     * <code>string image1 = 6;</code>
     * 
     * @param value The bytes for image1 to set.
     * @return This builder for chaining.
     */
    public Builder setImage1Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      image1_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private java.lang.Object image2_ = "";

    /**
     * <code>string image2 = 7;</code>
     * 
     * @return The image2.
     */
    public java.lang.String getImage2() {
      java.lang.Object ref = image2_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image2_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string image2 = 7;</code>
     * 
     * @return The bytes for image2.
     */
    public com.google.protobuf.ByteString getImage2Bytes() {
      java.lang.Object ref = image2_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        image2_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string image2 = 7;</code>
     * 
     * @param value The image2 to set.
     * @return This builder for chaining.
     */
    public Builder setImage2(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      image2_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    /**
     * <code>string image2 = 7;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearImage2() {
      image2_ = getDefaultInstance().getImage2();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }

    /**
     * <code>string image2 = 7;</code>
     * 
     * @param value The bytes for image2 to set.
     * @return This builder for chaining.
     */
    public Builder setImage2Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      image2_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private java.lang.Object image3_ = "";

    /**
     * <code>string image3 = 8;</code>
     * 
     * @return The image3.
     */
    public java.lang.String getImage3() {
      java.lang.Object ref = image3_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image3_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string image3 = 8;</code>
     * 
     * @return The bytes for image3.
     */
    public com.google.protobuf.ByteString getImage3Bytes() {
      java.lang.Object ref = image3_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        image3_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string image3 = 8;</code>
     * 
     * @param value The image3 to set.
     * @return This builder for chaining.
     */
    public Builder setImage3(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      image3_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    /**
     * <code>string image3 = 8;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearImage3() {
      image3_ = getDefaultInstance().getImage3();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }

    /**
     * <code>string image3 = 8;</code>
     * 
     * @param value The bytes for image3 to set.
     * @return This builder for chaining.
     */
    public Builder setImage3Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      image3_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object image4_ = "";

    /**
     * <code>string image4 = 9;</code>
     * 
     * @return The image4.
     */
    public java.lang.String getImage4() {
      java.lang.Object ref = image4_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        image4_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string image4 = 9;</code>
     * 
     * @return The bytes for image4.
     */
    public com.google.protobuf.ByteString getImage4Bytes() {
      java.lang.Object ref = image4_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        image4_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string image4 = 9;</code>
     * 
     * @param value The image4 to set.
     * @return This builder for chaining.
     */
    public Builder setImage4(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      image4_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    /**
     * <code>string image4 = 9;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearImage4() {
      image4_ = getDefaultInstance().getImage4();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }

    /**
     * <code>string image4 = 9;</code>
     * 
     * @param value The bytes for image4 to set.
     * @return This builder for chaining.
     */
    public Builder setImage4Bytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      image4_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.lang.Object destinations_ = "";

    /**
     * <code>string destinations = 10;</code>
     * 
     * @return The destinations.
     */
    public java.lang.String getDestinations() {
      java.lang.Object ref = destinations_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        destinations_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string destinations = 10;</code>
     * 
     * @return The bytes for destinations.
     */
    public com.google.protobuf.ByteString getDestinationsBytes() {
      java.lang.Object ref = destinations_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        destinations_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string destinations = 10;</code>
     * 
     * @param value The destinations to set.
     * @return This builder for chaining.
     */
    public Builder setDestinations(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      destinations_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    /**
     * <code>string destinations = 10;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearDestinations() {
      destinations_ = getDefaultInstance().getDestinations();
      bitField0_ = (bitField0_ & ~0x00000200);
      onChanged();
      return this;
    }

    /**
     * <code>string destinations = 10;</code>
     * 
     * @param value The bytes for destinations to set.
     * @return This builder for chaining.
     */
    public Builder setDestinationsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      destinations_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    private java.lang.Object duration_ = "";

    /**
     * <code>string duration = 11;</code>
     * 
     * @return The duration.
     */
    public java.lang.String getDuration() {
      java.lang.Object ref = duration_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        duration_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string duration = 11;</code>
     * 
     * @return The bytes for duration.
     */
    public com.google.protobuf.ByteString getDurationBytes() {
      java.lang.Object ref = duration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        duration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string duration = 11;</code>
     * 
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      duration_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    /**
     * <code>string duration = 11;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      duration_ = getDefaultInstance().getDuration();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }

    /**
     * <code>string duration = 11;</code>
     * 
     * @param value The bytes for duration to set.
     * @return This builder for chaining.
     */
    public Builder setDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      duration_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object departureTime_ = "";

    /**
     * <code>string departure_time = 12;</code>
     * 
     * @return The departureTime.
     */
    public java.lang.String getDepartureTime() {
      java.lang.Object ref = departureTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departureTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string departure_time = 12;</code>
     * 
     * @return The bytes for departureTime.
     */
    public com.google.protobuf.ByteString getDepartureTimeBytes() {
      java.lang.Object ref = departureTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        departureTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string departure_time = 12;</code>
     * 
     * @param value The departureTime to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureTime(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      departureTime_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    /**
     * <code>string departure_time = 12;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearDepartureTime() {
      departureTime_ = getDefaultInstance().getDepartureTime();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }

    /**
     * <code>string departure_time = 12;</code>
     * 
     * @param value The bytes for departureTime to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      departureTime_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private java.lang.Object departureLocation_ = "";

    /**
     * <code>string departure_location = 13;</code>
     * 
     * @return The departureLocation.
     */
    public java.lang.String getDepartureLocation() {
      java.lang.Object ref = departureLocation_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        departureLocation_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string departure_location = 13;</code>
     * 
     * @return The bytes for departureLocation.
     */
    public com.google.protobuf.ByteString getDepartureLocationBytes() {
      java.lang.Object ref = departureLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        departureLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string departure_location = 13;</code>
     * 
     * @param value The departureLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLocation(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      departureLocation_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    /**
     * <code>string departure_location = 13;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearDepartureLocation() {
      departureLocation_ = getDefaultInstance().getDepartureLocation();
      bitField0_ = (bitField0_ & ~0x00001000);
      onChanged();
      return this;
    }

    /**
     * <code>string departure_location = 13;</code>
     * 
     * @param value The bytes for departureLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      departureLocation_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }

    private java.lang.Object schedules_ = "";

    /**
     * <code>string schedules = 14;</code>
     * 
     * @return The schedules.
     */
    public java.lang.String getSchedules() {
      java.lang.Object ref = schedules_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        schedules_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string schedules = 14;</code>
     * 
     * @return The bytes for schedules.
     */
    public com.google.protobuf.ByteString getSchedulesBytes() {
      java.lang.Object ref = schedules_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        schedules_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string schedules = 14;</code>
     * 
     * @param value The schedules to set.
     * @return This builder for chaining.
     */
    public Builder setSchedules(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      schedules_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    /**
     * <code>string schedules = 14;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearSchedules() {
      schedules_ = getDefaultInstance().getSchedules();
      bitField0_ = (bitField0_ & ~0x00002000);
      onChanged();
      return this;
    }

    /**
     * <code>string schedules = 14;</code>
     * 
     * @param value The bytes for schedules to set.
     * @return This builder for chaining.
     */
    public Builder setSchedulesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      schedules_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }

    private java.lang.Object vehicle_ = "";

    /**
     * <code>string vehicle = 15;</code>
     * 
     * @return The vehicle.
     */
    public java.lang.String getVehicle() {
      java.lang.Object ref = vehicle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehicle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string vehicle = 15;</code>
     * 
     * @return The bytes for vehicle.
     */
    public com.google.protobuf.ByteString getVehicleBytes() {
      java.lang.Object ref = vehicle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        vehicle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string vehicle = 15;</code>
     * 
     * @param value The vehicle to set.
     * @return This builder for chaining.
     */
    public Builder setVehicle(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      vehicle_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    /**
     * <code>string vehicle = 15;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearVehicle() {
      vehicle_ = getDefaultInstance().getVehicle();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }

    /**
     * <code>string vehicle = 15;</code>
     * 
     * @param value The bytes for vehicle to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      vehicle_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private java.lang.Object status_ = "";

    /**
     * <code>string status = 16;</code>
     * 
     * @return The status.
     */
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string status = 16;</code>
     * 
     * @return The bytes for status.
     */
    public com.google.protobuf.ByteString getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string status = 16;</code>
     * 
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      status_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }

    /**
     * <code>string status = 16;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      status_ = getDefaultInstance().getStatus();
      bitField0_ = (bitField0_ & ~0x00008000);
      onChanged();
      return this;
    }

    /**
     * <code>string status = 16;</code>
     * 
     * @param value The bytes for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      status_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }

    private int totalSeats_;

    /**
     * <code>int32 total_seats = 17;</code>
     * 
     * @return The totalSeats.
     */
    @java.lang.Override
    public int getTotalSeats() {
      return totalSeats_;
    }

    /**
     * <code>int32 total_seats = 17;</code>
     * 
     * @param value The totalSeats to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSeats(int value) {

      totalSeats_ = value;
      bitField0_ |= 0x00010000;
      onChanged();
      return this;
    }

    /**
     * <code>int32 total_seats = 17;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTotalSeats() {
      bitField0_ = (bitField0_ & ~0x00010000);
      totalSeats_ = 0;
      onChanged();
      return this;
    }

    private int availableSeats_;

    /**
     * <code>int32 available_seats = 18;</code>
     * 
     * @return The availableSeats.
     */
    @java.lang.Override
    public int getAvailableSeats() {
      return availableSeats_;
    }

    /**
     * <code>int32 available_seats = 18;</code>
     * 
     * @param value The availableSeats to set.
     * @return This builder for chaining.
     */
    public Builder setAvailableSeats(int value) {

      availableSeats_ = value;
      bitField0_ |= 0x00020000;
      onChanged();
      return this;
    }

    /**
     * <code>int32 available_seats = 18;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearAvailableSeats() {
      bitField0_ = (bitField0_ & ~0x00020000);
      availableSeats_ = 0;
      onChanged();
      return this;
    }

    private int adultPrice_;

    /**
     * <code>int32 adult_price = 19;</code>
     * 
     * @return The adultPrice.
     */
    @java.lang.Override
    public int getAdultPrice() {
      return adultPrice_;
    }

    /**
     * <code>int32 adult_price = 19;</code>
     * 
     * @param value The adultPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAdultPrice(int value) {

      adultPrice_ = value;
      bitField0_ |= 0x00040000;
      onChanged();
      return this;
    }

    /**
     * <code>int32 adult_price = 19;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearAdultPrice() {
      bitField0_ = (bitField0_ & ~0x00040000);
      adultPrice_ = 0;
      onChanged();
      return this;
    }

    private int childrenPrice_;

    /**
     * <code>int32 children_price = 20;</code>
     * 
     * @return The childrenPrice.
     */
    @java.lang.Override
    public int getChildrenPrice() {
      return childrenPrice_;
    }

    /**
     * <code>int32 children_price = 20;</code>
     * 
     * @param value The childrenPrice to set.
     * @return This builder for chaining.
     */
    public Builder setChildrenPrice(int value) {

      childrenPrice_ = value;
      bitField0_ |= 0x00080000;
      onChanged();
      return this;
    }

    /**
     * <code>int32 children_price = 20;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearChildrenPrice() {
      bitField0_ = (bitField0_ & ~0x00080000);
      childrenPrice_ = 0;
      onChanged();
      return this;
    }

    private int babyPrice_;

    /**
     * <code>int32 baby_price = 21;</code>
     * 
     * @return The babyPrice.
     */
    @java.lang.Override
    public int getBabyPrice() {
      return babyPrice_;
    }

    /**
     * <code>int32 baby_price = 21;</code>
     * 
     * @param value The babyPrice to set.
     * @return This builder for chaining.
     */
    public Builder setBabyPrice(int value) {

      babyPrice_ = value;
      bitField0_ |= 0x00100000;
      onChanged();
      return this;
    }

    /**
     * <code>int32 baby_price = 21;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearBabyPrice() {
      bitField0_ = (bitField0_ & ~0x00100000);
      babyPrice_ = 0;
      onChanged();
      return this;
    }

    private int tourGuideId_;

    /**
     * <code>int32 tour_guide_id = 22;</code>
     * 
     * @return The tourGuideId.
     */
    @java.lang.Override
    public int getTourGuideId() {
      return tourGuideId_;
    }

    /**
     * <code>int32 tour_guide_id = 22;</code>
     * 
     * @param value The tourGuideId to set.
     * @return This builder for chaining.
     */
    public Builder setTourGuideId(int value) {

      tourGuideId_ = value;
      bitField0_ |= 0x00200000;
      onChanged();
      return this;
    }

    /**
     * <code>int32 tour_guide_id = 22;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTourGuideId() {
      bitField0_ = (bitField0_ & ~0x00200000);
      tourGuideId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object createdTime_ = "";

    /**
     * <code>string created_time = 23;</code>
     * 
     * @return The createdTime.
     */
    public java.lang.String getCreatedTime() {
      java.lang.Object ref = createdTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }

    /**
     * <code>string created_time = 23;</code>
     * 
     * @return The bytes for createdTime.
     */
    public com.google.protobuf.ByteString getCreatedTimeBytes() {
      java.lang.Object ref = createdTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (java.lang.String) ref);
        createdTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string created_time = 23;</code>
     * 
     * @param value The createdTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedTime(
        java.lang.String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      createdTime_ = value;
      bitField0_ |= 0x00400000;
      onChanged();
      return this;
    }

    /**
     * <code>string created_time = 23;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearCreatedTime() {
      createdTime_ = getDefaultInstance().getCreatedTime();
      bitField0_ = (bitField0_ & ~0x00400000);
      onChanged();
      return this;
    }

    /**
     * <code>string created_time = 23;</code>
     * 
     * @param value The bytes for createdTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      createdTime_ = value;
      bitField0_ |= 0x00400000;
      onChanged();
      return this;
    }

    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:SubTourDetailsResponse)
  }

  // @@protoc_insertion_point(class_scope:SubTourDetailsResponse)
  private static final grpc.tour.SubTourDetailsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.tour.SubTourDetailsResponse();
  }

  public static grpc.tour.SubTourDetailsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubTourDetailsResponse> PARSER = new com.google.protobuf.AbstractParser<SubTourDetailsResponse>() {
    @java.lang.Override
    public SubTourDetailsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubTourDetailsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubTourDetailsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.tour.SubTourDetailsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
