// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/vnpay/vnpay-service.proto

// Protobuf Java Version: 3.25.1
package grpc.payment.vnpay;

public interface BookingIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:vnpay.BookingIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 booking_id = 1;</code>
   * @return The bookingId.
   */
  int getBookingId();
}
