// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/vnpay/vnpay-service.proto

// Protobuf Java Version: 3.25.1
package grpc.payment.vnpay;

/**
 * <pre>
 * Input gRPC message
 * </pre>
 *
 * Protobuf type {@code vnpay.PaymentResultRequest}
 */
public final class PaymentResultRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:vnpay.PaymentResultRequest)
    PaymentResultRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PaymentResultRequest.newBuilder() to construct.
  private PaymentResultRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PaymentResultRequest() {
    bank_ = "";
    cardType_ = "";
    orderInfo_ = "";
    payDate_ = "";
    transactionNo_ = "";
    responseCode_ = "";
    txnRef_ = "";
    amount_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new PaymentResultRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return VnpayService.internal_static_vnpay_PaymentResultRequest_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return VnpayService.internal_static_vnpay_PaymentResultRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            PaymentResultRequest.class, Builder.class);
  }

  public static final int BOOKING_ID_FIELD_NUMBER = 1;
  private int bookingId_ = 0;
  /**
   * <code>int32 booking_id = 1;</code>
   * @return The bookingId.
   */
  @Override
  public int getBookingId() {
    return bookingId_;
  }

  public static final int BANK_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object bank_ = "";
  /**
   * <code>string bank = 2;</code>
   * @return The bank.
   */
  @Override
  public String getBank() {
    Object ref = bank_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      bank_ = s;
      return s;
    }
  }
  /**
   * <code>string bank = 2;</code>
   * @return The bytes for bank.
   */
  @Override
  public com.google.protobuf.ByteString
      getBankBytes() {
    Object ref = bank_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      bank_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CARD_TYPE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object cardType_ = "";
  /**
   * <code>string card_type = 3;</code>
   * @return The cardType.
   */
  @Override
  public String getCardType() {
    Object ref = cardType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      cardType_ = s;
      return s;
    }
  }
  /**
   * <code>string card_type = 3;</code>
   * @return The bytes for cardType.
   */
  @Override
  public com.google.protobuf.ByteString
      getCardTypeBytes() {
    Object ref = cardType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      cardType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ORDER_INFO_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object orderInfo_ = "";
  /**
   * <code>string order_info = 4;</code>
   * @return The orderInfo.
   */
  @Override
  public String getOrderInfo() {
    Object ref = orderInfo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      orderInfo_ = s;
      return s;
    }
  }
  /**
   * <code>string order_info = 4;</code>
   * @return The bytes for orderInfo.
   */
  @Override
  public com.google.protobuf.ByteString
      getOrderInfoBytes() {
    Object ref = orderInfo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      orderInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAY_DATE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object payDate_ = "";
  /**
   * <code>string pay_date = 5;</code>
   * @return The payDate.
   */
  @Override
  public String getPayDate() {
    Object ref = payDate_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      payDate_ = s;
      return s;
    }
  }
  /**
   * <code>string pay_date = 5;</code>
   * @return The bytes for payDate.
   */
  @Override
  public com.google.protobuf.ByteString
      getPayDateBytes() {
    Object ref = payDate_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      payDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSACTION_NO_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile Object transactionNo_ = "";
  /**
   * <code>string transaction_no = 6;</code>
   * @return The transactionNo.
   */
  @Override
  public String getTransactionNo() {
    Object ref = transactionNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transactionNo_ = s;
      return s;
    }
  }
  /**
   * <code>string transaction_no = 6;</code>
   * @return The bytes for transactionNo.
   */
  @Override
  public com.google.protobuf.ByteString
      getTransactionNoBytes() {
    Object ref = transactionNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      transactionNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESPONSE_CODE_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private volatile Object responseCode_ = "";
  /**
   * <code>string response_code = 7;</code>
   * @return The responseCode.
   */
  @Override
  public String getResponseCode() {
    Object ref = responseCode_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      responseCode_ = s;
      return s;
    }
  }
  /**
   * <code>string response_code = 7;</code>
   * @return The bytes for responseCode.
   */
  @Override
  public com.google.protobuf.ByteString
      getResponseCodeBytes() {
    Object ref = responseCode_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      responseCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TXN_REF_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile Object txnRef_ = "";
  /**
   * <code>string txn_ref = 8;</code>
   * @return The txnRef.
   */
  @Override
  public String getTxnRef() {
    Object ref = txnRef_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      txnRef_ = s;
      return s;
    }
  }
  /**
   * <code>string txn_ref = 8;</code>
   * @return The bytes for txnRef.
   */
  @Override
  public com.google.protobuf.ByteString
      getTxnRefBytes() {
    Object ref = txnRef_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      txnRef_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AMOUNT_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile Object amount_ = "";
  /**
   * <code>string amount = 9;</code>
   * @return The amount.
   */
  @Override
  public String getAmount() {
    Object ref = amount_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      amount_ = s;
      return s;
    }
  }
  /**
   * <code>string amount = 9;</code>
   * @return The bytes for amount.
   */
  @Override
  public com.google.protobuf.ByteString
      getAmountBytes() {
    Object ref = amount_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      amount_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bookingId_ != 0) {
      output.writeInt32(1, bookingId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bank_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bank_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cardType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cardType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderInfo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, orderInfo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(payDate_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, payDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionNo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, transactionNo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, responseCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txnRef_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, txnRef_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, amount_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bookingId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, bookingId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(bank_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bank_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cardType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cardType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(orderInfo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, orderInfo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(payDate_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, payDate_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(transactionNo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, transactionNo_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(responseCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, responseCode_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(txnRef_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, txnRef_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(amount_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, amount_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof PaymentResultRequest)) {
      return super.equals(obj);
    }
    PaymentResultRequest other = (PaymentResultRequest) obj;

    if (getBookingId()
        != other.getBookingId()) return false;
    if (!getBank()
        .equals(other.getBank())) return false;
    if (!getCardType()
        .equals(other.getCardType())) return false;
    if (!getOrderInfo()
        .equals(other.getOrderInfo())) return false;
    if (!getPayDate()
        .equals(other.getPayDate())) return false;
    if (!getTransactionNo()
        .equals(other.getTransactionNo())) return false;
    if (!getResponseCode()
        .equals(other.getResponseCode())) return false;
    if (!getTxnRef()
        .equals(other.getTxnRef())) return false;
    if (!getAmount()
        .equals(other.getAmount())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKING_ID_FIELD_NUMBER;
    hash = (53 * hash) + getBookingId();
    hash = (37 * hash) + BANK_FIELD_NUMBER;
    hash = (53 * hash) + getBank().hashCode();
    hash = (37 * hash) + CARD_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getCardType().hashCode();
    hash = (37 * hash) + ORDER_INFO_FIELD_NUMBER;
    hash = (53 * hash) + getOrderInfo().hashCode();
    hash = (37 * hash) + PAY_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getPayDate().hashCode();
    hash = (37 * hash) + TRANSACTION_NO_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionNo().hashCode();
    hash = (37 * hash) + RESPONSE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getResponseCode().hashCode();
    hash = (37 * hash) + TXN_REF_FIELD_NUMBER;
    hash = (53 * hash) + getTxnRef().hashCode();
    hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAmount().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static PaymentResultRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PaymentResultRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PaymentResultRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PaymentResultRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PaymentResultRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static PaymentResultRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static PaymentResultRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PaymentResultRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static PaymentResultRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static PaymentResultRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static PaymentResultRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static PaymentResultRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(PaymentResultRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Input gRPC message
   * </pre>
   *
   * Protobuf type {@code vnpay.PaymentResultRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:vnpay.PaymentResultRequest)
      PaymentResultRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return VnpayService.internal_static_vnpay_PaymentResultRequest_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return VnpayService.internal_static_vnpay_PaymentResultRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PaymentResultRequest.class, Builder.class);
    }

    // Construct using grpc.payment.vnpay.PaymentResultRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bookingId_ = 0;
      bank_ = "";
      cardType_ = "";
      orderInfo_ = "";
      payDate_ = "";
      transactionNo_ = "";
      responseCode_ = "";
      txnRef_ = "";
      amount_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return VnpayService.internal_static_vnpay_PaymentResultRequest_descriptor;
    }

    @Override
    public PaymentResultRequest getDefaultInstanceForType() {
      return PaymentResultRequest.getDefaultInstance();
    }

    @Override
    public PaymentResultRequest build() {
      PaymentResultRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public PaymentResultRequest buildPartial() {
      PaymentResultRequest result = new PaymentResultRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(PaymentResultRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bookingId_ = bookingId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.bank_ = bank_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cardType_ = cardType_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.orderInfo_ = orderInfo_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.payDate_ = payDate_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.transactionNo_ = transactionNo_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.responseCode_ = responseCode_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.txnRef_ = txnRef_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.amount_ = amount_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof PaymentResultRequest) {
        return mergeFrom((PaymentResultRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(PaymentResultRequest other) {
      if (other == PaymentResultRequest.getDefaultInstance()) return this;
      if (other.getBookingId() != 0) {
        setBookingId(other.getBookingId());
      }
      if (!other.getBank().isEmpty()) {
        bank_ = other.bank_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getCardType().isEmpty()) {
        cardType_ = other.cardType_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getOrderInfo().isEmpty()) {
        orderInfo_ = other.orderInfo_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getPayDate().isEmpty()) {
        payDate_ = other.payDate_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getTransactionNo().isEmpty()) {
        transactionNo_ = other.transactionNo_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.getResponseCode().isEmpty()) {
        responseCode_ = other.responseCode_;
        bitField0_ |= 0x00000040;
        onChanged();
      }
      if (!other.getTxnRef().isEmpty()) {
        txnRef_ = other.txnRef_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (!other.getAmount().isEmpty()) {
        amount_ = other.amount_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bookingId_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              bank_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              cardType_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              orderInfo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              payDate_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              transactionNo_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              responseCode_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 66: {
              txnRef_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              amount_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int bookingId_ ;
    /**
     * <code>int32 booking_id = 1;</code>
     * @return The bookingId.
     */
    @Override
    public int getBookingId() {
      return bookingId_;
    }
    /**
     * <code>int32 booking_id = 1;</code>
     * @param value The bookingId to set.
     * @return This builder for chaining.
     */
    public Builder setBookingId(int value) {

      bookingId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 booking_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBookingId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bookingId_ = 0;
      onChanged();
      return this;
    }

    private Object bank_ = "";
    /**
     * <code>string bank = 2;</code>
     * @return The bank.
     */
    public String getBank() {
      Object ref = bank_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        bank_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string bank = 2;</code>
     * @return The bytes for bank.
     */
    public com.google.protobuf.ByteString
        getBankBytes() {
      Object ref = bank_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        bank_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bank = 2;</code>
     * @param value The bank to set.
     * @return This builder for chaining.
     */
    public Builder setBank(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      bank_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string bank = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBank() {
      bank_ = getDefaultInstance().getBank();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string bank = 2;</code>
     * @param value The bytes for bank to set.
     * @return This builder for chaining.
     */
    public Builder setBankBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bank_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object cardType_ = "";
    /**
     * <code>string card_type = 3;</code>
     * @return The cardType.
     */
    public String getCardType() {
      Object ref = cardType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cardType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string card_type = 3;</code>
     * @return The bytes for cardType.
     */
    public com.google.protobuf.ByteString
        getCardTypeBytes() {
      Object ref = cardType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cardType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string card_type = 3;</code>
     * @param value The cardType to set.
     * @return This builder for chaining.
     */
    public Builder setCardType(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      cardType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string card_type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCardType() {
      cardType_ = getDefaultInstance().getCardType();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string card_type = 3;</code>
     * @param value The bytes for cardType to set.
     * @return This builder for chaining.
     */
    public Builder setCardTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      cardType_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object orderInfo_ = "";
    /**
     * <code>string order_info = 4;</code>
     * @return The orderInfo.
     */
    public String getOrderInfo() {
      Object ref = orderInfo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        orderInfo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string order_info = 4;</code>
     * @return The bytes for orderInfo.
     */
    public com.google.protobuf.ByteString
        getOrderInfoBytes() {
      Object ref = orderInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string order_info = 4;</code>
     * @param value The orderInfo to set.
     * @return This builder for chaining.
     */
    public Builder setOrderInfo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      orderInfo_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string order_info = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOrderInfo() {
      orderInfo_ = getDefaultInstance().getOrderInfo();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string order_info = 4;</code>
     * @param value The bytes for orderInfo to set.
     * @return This builder for chaining.
     */
    public Builder setOrderInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      orderInfo_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object payDate_ = "";
    /**
     * <code>string pay_date = 5;</code>
     * @return The payDate.
     */
    public String getPayDate() {
      Object ref = payDate_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        payDate_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string pay_date = 5;</code>
     * @return The bytes for payDate.
     */
    public com.google.protobuf.ByteString
        getPayDateBytes() {
      Object ref = payDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        payDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string pay_date = 5;</code>
     * @param value The payDate to set.
     * @return This builder for chaining.
     */
    public Builder setPayDate(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      payDate_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string pay_date = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayDate() {
      payDate_ = getDefaultInstance().getPayDate();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string pay_date = 5;</code>
     * @param value The bytes for payDate to set.
     * @return This builder for chaining.
     */
    public Builder setPayDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      payDate_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private Object transactionNo_ = "";
    /**
     * <code>string transaction_no = 6;</code>
     * @return The transactionNo.
     */
    public String getTransactionNo() {
      Object ref = transactionNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transactionNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string transaction_no = 6;</code>
     * @return The bytes for transactionNo.
     */
    public com.google.protobuf.ByteString
        getTransactionNoBytes() {
      Object ref = transactionNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transactionNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transaction_no = 6;</code>
     * @param value The transactionNo to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionNo(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      transactionNo_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_no = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTransactionNo() {
      transactionNo_ = getDefaultInstance().getTransactionNo();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string transaction_no = 6;</code>
     * @param value The bytes for transactionNo to set.
     * @return This builder for chaining.
     */
    public Builder setTransactionNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transactionNo_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private Object responseCode_ = "";
    /**
     * <code>string response_code = 7;</code>
     * @return The responseCode.
     */
    public String getResponseCode() {
      Object ref = responseCode_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        responseCode_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string response_code = 7;</code>
     * @return The bytes for responseCode.
     */
    public com.google.protobuf.ByteString
        getResponseCodeBytes() {
      Object ref = responseCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        responseCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string response_code = 7;</code>
     * @param value The responseCode to set.
     * @return This builder for chaining.
     */
    public Builder setResponseCode(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      responseCode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>string response_code = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearResponseCode() {
      responseCode_ = getDefaultInstance().getResponseCode();
      bitField0_ = (bitField0_ & ~0x00000040);
      onChanged();
      return this;
    }
    /**
     * <code>string response_code = 7;</code>
     * @param value The bytes for responseCode to set.
     * @return This builder for chaining.
     */
    public Builder setResponseCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      responseCode_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private Object txnRef_ = "";
    /**
     * <code>string txn_ref = 8;</code>
     * @return The txnRef.
     */
    public String getTxnRef() {
      Object ref = txnRef_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        txnRef_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string txn_ref = 8;</code>
     * @return The bytes for txnRef.
     */
    public com.google.protobuf.ByteString
        getTxnRefBytes() {
      Object ref = txnRef_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        txnRef_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string txn_ref = 8;</code>
     * @param value The txnRef to set.
     * @return This builder for chaining.
     */
    public Builder setTxnRef(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      txnRef_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string txn_ref = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTxnRef() {
      txnRef_ = getDefaultInstance().getTxnRef();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string txn_ref = 8;</code>
     * @param value The bytes for txnRef to set.
     * @return This builder for chaining.
     */
    public Builder setTxnRefBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      txnRef_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private Object amount_ = "";
    /**
     * <code>string amount = 9;</code>
     * @return The amount.
     */
    public String getAmount() {
      Object ref = amount_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        amount_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string amount = 9;</code>
     * @return The bytes for amount.
     */
    public com.google.protobuf.ByteString
        getAmountBytes() {
      Object ref = amount_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        amount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string amount = 9;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(
        String value) {
      if (value == null) { throw new NullPointerException(); }
      amount_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      amount_ = getDefaultInstance().getAmount();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>string amount = 9;</code>
     * @param value The bytes for amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      amount_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:vnpay.PaymentResultRequest)
  }

  // @@protoc_insertion_point(class_scope:vnpay.PaymentResultRequest)
  private static final PaymentResultRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new PaymentResultRequest();
  }

  public static PaymentResultRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaymentResultRequest>
      PARSER = new com.google.protobuf.AbstractParser<PaymentResultRequest>() {
    @Override
    public PaymentResultRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PaymentResultRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<PaymentResultRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public PaymentResultRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

