// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking/v2/dto/response/get-booking-by-id-response.proto

// Protobuf Java Version: 3.25.1
package grpc.booking.v2.dto.response;

public final class GetBookingByIdResponseOuterClass {
  private GetBookingByIdResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_GetBookingByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_GetBookingByIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n8booking/v2/dto/response/get-booking-by" +
      "-id-response.proto\022\010response\032\036booking/v2" +
      "/model/booking.proto\"9\n\026GetBookingByIdRe" +
      "sponse\022\037\n\007booking\030\001 \001(\0132\016.model.BookingB" +
      " \n\034grpc.booking.v2.dto.responseP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.booking.v2.model.BookingOuterClass.getDescriptor(),
        });
    internal_static_response_GetBookingByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_GetBookingByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_GetBookingByIdResponse_descriptor,
        new String[] { "Booking", });
    grpc.booking.v2.model.BookingOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
