// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/dto/response/check-profile-by-email-response.proto

// Protobuf Java Version: 3.25.1
package grpc.account.dto.response;

public interface CheckProfileByEmailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response.CheckProfileByEmailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_exists_email = 1;</code>
   * 
   * @return The isExistsEmail.
   */
  boolean getIsExistsEmail();

  /**
   * <code>.response.ProfileResponse profile = 2;</code>
   * 
   * @return Whether the profile field is set.
   */
  boolean hasProfile();

  /**
   * <code>.response.ProfileResponse profile = 2;</code>
   * 
   * @return The profile.
   */
  ProfileResponse getProfile();

  /**
   * <code>.response.ProfileResponse profile = 2;</code>
   */
  ProfileResponseOrBuilder getProfileOrBuilder();
}
