// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking/v2/service/booking-checking.proto

// Protobuf Java Version: 3.25.1
package grpc.booking.v2.service;

public final class BookingChecking {
  private BookingChecking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n)booking/v2/service/booking-checking.pr" +
      "oto\022\007service\0328booking/v2/dto/request/che" +
      "ck-booking-by-id-request.proto\032:booking/" +
      "v2/dto/response/check-booking-by-id-resp" +
      "onse.proto2t\n\026BookingCheckingService\022Z\n\020" +
      "CheckBookingById\022 .request.CheckBookingB" +
      "yIdRequest\032\".response.CheckBookingByIdRe" +
      "sponse\"\000B\033\n\027grpc.booking.v2.serviceP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.booking.v2.dto.request.CheckBookingByIdRequestOuterClass.getDescriptor(),
          grpc.booking.v2.dto.response.CheckBookingByIdResponseOuterClass.getDescriptor(),
        });
    grpc.booking.v2.dto.request.CheckBookingByIdRequestOuterClass.getDescriptor();
    grpc.booking.v2.dto.response.CheckBookingByIdResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
