// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/response/get-account-by-email-response.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.response;

public interface GetAccountByEmailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response.GetAccountByEmailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.response.AccountResponse account = 1;</code>
   * 
   * @return Whether the account field is set.
   */
  boolean hasAccount();

  /**
   * <code>.response.AccountResponse account = 1;</code>
   * 
   * @return The account.
   */
  AccountResponse getAccount();

  /**
   * <code>.response.AccountResponse account = 1;</code>
   */
  AccountResponseOrBuilder getAccountOrBuilder();
}
