server:
  port: 8084
spring:
  application:
    name: booking-service
  liquibase:
    url: jdbc:mysql://mysql-server:3306/bk_travel_booking
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  instance:
    hostname: booking-service
    appname: booking-service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
bk-travel:
  config:
    database:
      server:
        url: r2dbc:mysql://mysql-server:3306/bk_travel_booking
        username: root
        password: root
grpc:
  server:
    port: 50084
kafka:
  bootstrap-servers:
    url: http://kafka-broker-01:19092
  consumer:
    group-id: bk-travel-group
    auto-offset-reset: latest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer