// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour/dto/response/check-tour-by-id-response.proto

// Protobuf Java Version: 3.25.1
package grpc.tour.dto.response;

/**
 * Protobuf type {@code response.CheckTourByIdResponse}
 */
public final class CheckTourByIdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:response.CheckTourByIdResponse)
    CheckTourByIdResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use CheckTourByIdResponse.newBuilder() to construct.
  private CheckTourByIdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private CheckTourByIdResponse() {
  }

  @Override
  @SuppressWarnings({ "unused" })
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckTourByIdResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return CheckTourByIdResponseOuterClass.internal_static_response_CheckTourByIdResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return CheckTourByIdResponseOuterClass.internal_static_response_CheckTourByIdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CheckTourByIdResponse.class, Builder.class);
  }

  private int bitField0_;
  public static final int IS_EXISTS_FIELD_NUMBER = 1;
  private boolean isExists_ = false;

  /**
   * <code>bool is_exists = 1;</code>
   * 
   * @return The isExists.
   */
  @Override
  public boolean getIsExists() {
    return isExists_;
  }

  public static final int TOUR_FIELD_NUMBER = 2;
  private TourResponse tour_;

  /**
   * <code>.response.TourResponse tour = 2;</code>
   * 
   * @return Whether the tour field is set.
   */
  @Override
  public boolean hasTour() {
    return ((bitField0_ & 0x00000001) != 0);
  }

  /**
   * <code>.response.TourResponse tour = 2;</code>
   * 
   * @return The tour.
   */
  @Override
  public TourResponse getTour() {
    return tour_ == null ? TourResponse.getDefaultInstance() : tour_;
  }

  /**
   * <code>.response.TourResponse tour = 2;</code>
   */
  @Override
  public TourResponseOrBuilder getTourOrBuilder() {
    return tour_ == null ? TourResponse.getDefaultInstance() : tour_;
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (isExists_ != false) {
      output.writeBool(1, isExists_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getTour());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (isExists_ != false) {
      size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isExists_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTour());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof CheckTourByIdResponse)) {
      return super.equals(obj);
    }
    CheckTourByIdResponse other = (CheckTourByIdResponse) obj;

    if (getIsExists() != other.getIsExists())
      return false;
    if (hasTour() != other.hasTour())
      return false;
    if (hasTour()) {
      if (!getTour()
          .equals(other.getTour()))
        return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields()))
      return false;
    return true;
  }

  @SuppressWarnings("unchecked")
  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_EXISTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsExists());
    if (hasTour()) {
      hash = (37 * hash) + TOUR_FIELD_NUMBER;
      hash = (53 * hash) + getTour().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CheckTourByIdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CheckTourByIdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CheckTourByIdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CheckTourByIdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CheckTourByIdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static CheckTourByIdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static CheckTourByIdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static CheckTourByIdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CheckTourByIdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CheckTourByIdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static CheckTourByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static CheckTourByIdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(CheckTourByIdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder()
        : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code response.CheckTourByIdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:response.CheckTourByIdResponse)
      CheckTourByIdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return CheckTourByIdResponseOuterClass.internal_static_response_CheckTourByIdResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return CheckTourByIdResponseOuterClass.internal_static_response_CheckTourByIdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CheckTourByIdResponse.class, Builder.class);
    }

    // Construct using grpc.tour.dto.response.CheckTourByIdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }

    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        getTourFieldBuilder();
      }
    }

    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isExists_ = false;
      tour_ = null;
      if (tourBuilder_ != null) {
        tourBuilder_.dispose();
        tourBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return CheckTourByIdResponseOuterClass.internal_static_response_CheckTourByIdResponse_descriptor;
    }

    @Override
    public CheckTourByIdResponse getDefaultInstanceForType() {
      return CheckTourByIdResponse.getDefaultInstance();
    }

    @Override
    public CheckTourByIdResponse build() {
      CheckTourByIdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CheckTourByIdResponse buildPartial() {
      CheckTourByIdResponse result = new CheckTourByIdResponse(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(CheckTourByIdResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isExists_ = isExists_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tour_ = tourBuilder_ == null
            ? tour_
            : tourBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CheckTourByIdResponse) {
        return mergeFrom((CheckTourByIdResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CheckTourByIdResponse other) {
      if (other == CheckTourByIdResponse.getDefaultInstance())
        return this;
      if (other.getIsExists() != false) {
        setIsExists(other.getIsExists());
      }
      if (other.hasTour()) {
        mergeTour(other.getTour());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isExists_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getTourFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private boolean isExists_;

    /**
     * <code>bool is_exists = 1;</code>
     * 
     * @return The isExists.
     */
    @Override
    public boolean getIsExists() {
      return isExists_;
    }

    /**
     * <code>bool is_exists = 1;</code>
     * 
     * @param value The isExists to set.
     * @return This builder for chaining.
     */
    public Builder setIsExists(boolean value) {

      isExists_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>bool is_exists = 1;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearIsExists() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isExists_ = false;
      onChanged();
      return this;
    }

    private TourResponse tour_;
    private com.google.protobuf.SingleFieldBuilderV3<TourResponse, TourResponse.Builder, TourResponseOrBuilder> tourBuilder_;

    /**
     * <code>.response.TourResponse tour = 2;</code>
     * 
     * @return Whether the tour field is set.
     */
    public boolean hasTour() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     * 
     * @return The tour.
     */
    public TourResponse getTour() {
      if (tourBuilder_ == null) {
        return tour_ == null ? TourResponse.getDefaultInstance() : tour_;
      } else {
        return tourBuilder_.getMessage();
      }
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    public Builder setTour(TourResponse value) {
      if (tourBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tour_ = value;
      } else {
        tourBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    public Builder setTour(
        TourResponse.Builder builderForValue) {
      if (tourBuilder_ == null) {
        tour_ = builderForValue.build();
      } else {
        tourBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    public Builder mergeTour(TourResponse value) {
      if (tourBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            tour_ != null &&
            tour_ != TourResponse.getDefaultInstance()) {
          getTourBuilder().mergeFrom(value);
        } else {
          tour_ = value;
        }
      } else {
        tourBuilder_.mergeFrom(value);
      }
      if (tour_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    public Builder clearTour() {
      bitField0_ = (bitField0_ & ~0x00000002);
      tour_ = null;
      if (tourBuilder_ != null) {
        tourBuilder_.dispose();
        tourBuilder_ = null;
      }
      onChanged();
      return this;
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    public TourResponse.Builder getTourBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getTourFieldBuilder().getBuilder();
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    public TourResponseOrBuilder getTourOrBuilder() {
      if (tourBuilder_ != null) {
        return tourBuilder_.getMessageOrBuilder();
      } else {
        return tour_ == null ? TourResponse.getDefaultInstance() : tour_;
      }
    }

    /**
     * <code>.response.TourResponse tour = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<TourResponse, TourResponse.Builder, TourResponseOrBuilder> getTourFieldBuilder() {
      if (tourBuilder_ == null) {
        tourBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<TourResponse, TourResponse.Builder, TourResponseOrBuilder>(
            getTour(),
            getParentForChildren(),
            isClean());
        tour_ = null;
      }
      return tourBuilder_;
    }

    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:response.CheckTourByIdResponse)
  }

  // @@protoc_insertion_point(class_scope:response.CheckTourByIdResponse)
  private static final CheckTourByIdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CheckTourByIdResponse();
  }

  public static CheckTourByIdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckTourByIdResponse> PARSER = new com.google.protobuf.AbstractParser<CheckTourByIdResponse>() {
    @Override
    public CheckTourByIdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckTourByIdResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CheckTourByIdResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public CheckTourByIdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
