// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour/dto/response/tour-response.proto

// Protobuf Java Version: 3.25.1
package grpc.tour.dto.response;

/**
 * Protobuf type {@code response.TourResponse}
 */
public final class TourResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:response.TourResponse)
    TourResponseOrBuilder {
  private static final long serialVersionUID = 0L;

  // Use TourResponse.newBuilder() to construct.
  private TourResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }

  private TourResponse() {
    title_ = "";
    duration_ = "";
    departureLocation_ = "";
    vehicle_ = "";
    createdTime_ = "";
  }

  @Override
  @SuppressWarnings({ "unused" })
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TourResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
    return TourResponseOuterClass.internal_static_response_TourResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable internalGetFieldAccessorTable() {
    return TourResponseOuterClass.internal_static_response_TourResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TourResponse.class, Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;

  /**
   * <code>int32 id = 1;</code>
   * 
   * @return The id.
   */
  @Override
  public int getId() {
    return id_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile Object title_ = "";

  /**
   * <code>string title = 2;</code>
   * 
   * @return The title.
   */
  @Override
  public String getTitle() {
    Object ref = title_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }

  /**
   * <code>string title = 2;</code>
   * 
   * @return The bytes for title.
   */
  @Override
  public com.google.protobuf.ByteString getTitleBytes() {
    Object ref = title_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DURATION_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile Object duration_ = "";

  /**
   * <code>string duration = 3;</code>
   * 
   * @return The duration.
   */
  @Override
  public String getDuration() {
    Object ref = duration_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      duration_ = s;
      return s;
    }
  }

  /**
   * <code>string duration = 3;</code>
   * 
   * @return The bytes for duration.
   */
  @Override
  public com.google.protobuf.ByteString getDurationBytes() {
    Object ref = duration_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (String) ref);
      duration_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEPARTURE_LOCATION_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile Object departureLocation_ = "";

  /**
   * <code>string departure_location = 4;</code>
   * 
   * @return The departureLocation.
   */
  @Override
  public String getDepartureLocation() {
    Object ref = departureLocation_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      departureLocation_ = s;
      return s;
    }
  }

  /**
   * <code>string departure_location = 4;</code>
   * 
   * @return The bytes for departureLocation.
   */
  @Override
  public com.google.protobuf.ByteString getDepartureLocationBytes() {
    Object ref = departureLocation_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (String) ref);
      departureLocation_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VEHICLE_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile Object vehicle_ = "";

  /**
   * <code>string vehicle = 5;</code>
   * 
   * @return The vehicle.
   */
  @Override
  public String getVehicle() {
    Object ref = vehicle_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      vehicle_ = s;
      return s;
    }
  }

  /**
   * <code>string vehicle = 5;</code>
   * 
   * @return The bytes for vehicle.
   */
  @Override
  public com.google.protobuf.ByteString getVehicleBytes() {
    Object ref = vehicle_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (String) ref);
      vehicle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_SEATS_FIELD_NUMBER = 6;
  private int totalSeats_ = 0;

  /**
   * <code>int32 total_seats = 6;</code>
   * 
   * @return The totalSeats.
   */
  @Override
  public int getTotalSeats() {
    return totalSeats_;
  }

  public static final int ADULT_PRICE_FIELD_NUMBER = 7;
  private int adultPrice_ = 0;

  /**
   * <code>int32 adult_price = 7;</code>
   * 
   * @return The adultPrice.
   */
  @Override
  public int getAdultPrice() {
    return adultPrice_;
  }

  public static final int CHILDREN_PRICE_FIELD_NUMBER = 8;
  private int childrenPrice_ = 0;

  /**
   * <code>int32 children_price = 8;</code>
   * 
   * @return The childrenPrice.
   */
  @Override
  public int getChildrenPrice() {
    return childrenPrice_;
  }

  public static final int BABY_PRICE_FIELD_NUMBER = 9;
  private int babyPrice_ = 0;

  /**
   * <code>int32 baby_price = 9;</code>
   * 
   * @return The babyPrice.
   */
  @Override
  public int getBabyPrice() {
    return babyPrice_;
  }

  public static final int TOTAL_SUB_TOURS_FIELD_NUMBER = 10;
  private int totalSubTours_ = 0;

  /**
   * <code>int32 total_sub_tours = 10;</code>
   * 
   * @return The totalSubTours.
   */
  @Override
  public int getTotalSubTours() {
    return totalSubTours_;
  }

  public static final int CREATED_TIME_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile Object createdTime_ = "";

  /**
   * <code>string created_time = 11;</code>
   * 
   * @return The createdTime.
   */
  @Override
  public String getCreatedTime() {
    Object ref = createdTime_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      createdTime_ = s;
      return s;
    }
  }

  /**
   * <code>string created_time = 11;</code>
   * 
   * @return The bytes for createdTime.
   */
  @Override
  public com.google.protobuf.ByteString getCreatedTimeBytes() {
    Object ref = createdTime_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
          (String) ref);
      createdTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;

  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1)
      return true;
    if (isInitialized == 0)
      return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
      throws java.io.IOException {
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(duration_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, duration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLocation_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, departureLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, vehicle_);
    }
    if (totalSeats_ != 0) {
      output.writeInt32(6, totalSeats_);
    }
    if (adultPrice_ != 0) {
      output.writeInt32(7, adultPrice_);
    }
    if (childrenPrice_ != 0) {
      output.writeInt32(8, childrenPrice_);
    }
    if (babyPrice_ != 0) {
      output.writeInt32(9, babyPrice_);
    }
    if (totalSubTours_ != 0) {
      output.writeInt32(10, totalSubTours_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdTime_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, createdTime_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1)
      return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(duration_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, duration_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(departureLocation_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, departureLocation_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(vehicle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, vehicle_);
    }
    if (totalSeats_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, totalSeats_);
    }
    if (adultPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, adultPrice_);
    }
    if (childrenPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, childrenPrice_);
    }
    if (babyPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, babyPrice_);
    }
    if (totalSubTours_ != 0) {
      size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, totalSubTours_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdTime_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, createdTime_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
      return true;
    }
    if (!(obj instanceof TourResponse)) {
      return super.equals(obj);
    }
    TourResponse other = (TourResponse) obj;

    if (getId() != other.getId())
      return false;
    if (!getTitle()
        .equals(other.getTitle()))
      return false;
    if (!getDuration()
        .equals(other.getDuration()))
      return false;
    if (!getDepartureLocation()
        .equals(other.getDepartureLocation()))
      return false;
    if (!getVehicle()
        .equals(other.getVehicle()))
      return false;
    if (getTotalSeats() != other.getTotalSeats())
      return false;
    if (getAdultPrice() != other.getAdultPrice())
      return false;
    if (getChildrenPrice() != other.getChildrenPrice())
      return false;
    if (getBabyPrice() != other.getBabyPrice())
      return false;
    if (getTotalSubTours() != other.getTotalSubTours())
      return false;
    if (!getCreatedTime()
        .equals(other.getCreatedTime()))
      return false;
    if (!getUnknownFields().equals(other.getUnknownFields()))
      return false;
    return true;
  }

  @SuppressWarnings("unchecked")
  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + getDuration().hashCode();
    hash = (37 * hash) + DEPARTURE_LOCATION_FIELD_NUMBER;
    hash = (53 * hash) + getDepartureLocation().hashCode();
    hash = (37 * hash) + VEHICLE_FIELD_NUMBER;
    hash = (53 * hash) + getVehicle().hashCode();
    hash = (37 * hash) + TOTAL_SEATS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSeats();
    hash = (37 * hash) + ADULT_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getAdultPrice();
    hash = (37 * hash) + CHILDREN_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getChildrenPrice();
    hash = (37 * hash) + BABY_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getBabyPrice();
    hash = (37 * hash) + TOTAL_SUB_TOURS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalSubTours();
    hash = (37 * hash) + CREATED_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedTime().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TourResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static TourResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static TourResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static TourResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static TourResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }

  public static TourResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }

  public static TourResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static TourResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static TourResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static TourResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }

  public static TourResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }

  public static TourResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() {
    return newBuilder();
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }

  public static Builder newBuilder(TourResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder()
        : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }

  /**
   * Protobuf type {@code response.TourResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:response.TourResponse)
      TourResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return TourResponseOuterClass.internal_static_response_TourResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable internalGetFieldAccessorTable() {
      return TourResponseOuterClass.internal_static_response_TourResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TourResponse.class, Builder.class);
    }

    // Construct using grpc.tour.dto.response.TourResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        BuilderParent parent) {
      super(parent);

    }

    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      title_ = "";
      duration_ = "";
      departureLocation_ = "";
      vehicle_ = "";
      totalSeats_ = 0;
      adultPrice_ = 0;
      childrenPrice_ = 0;
      babyPrice_ = 0;
      totalSubTours_ = 0;
      createdTime_ = "";
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return TourResponseOuterClass.internal_static_response_TourResponse_descriptor;
    }

    @Override
    public TourResponse getDefaultInstanceForType() {
      return TourResponse.getDefaultInstance();
    }

    @Override
    public TourResponse build() {
      TourResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TourResponse buildPartial() {
      TourResponse result = new TourResponse(this);
      if (bitField0_ != 0) {
        buildPartial0(result);
      }
      onBuilt();
      return result;
    }

    private void buildPartial0(TourResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.duration_ = duration_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.departureLocation_ = departureLocation_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.vehicle_ = vehicle_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.totalSeats_ = totalSeats_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.adultPrice_ = adultPrice_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.childrenPrice_ = childrenPrice_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.babyPrice_ = babyPrice_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.totalSubTours_ = totalSubTours_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.createdTime_ = createdTime_;
      }
    }

    @Override
    public Builder clone() {
      return super.clone();
    }

    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }

    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }

    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }

    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }

    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }

    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TourResponse) {
        return mergeFrom((TourResponse) other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TourResponse other) {
      if (other == TourResponse.getDefaultInstance())
        return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDuration().isEmpty()) {
        duration_ = other.duration_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getDepartureLocation().isEmpty()) {
        departureLocation_ = other.departureLocation_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getVehicle().isEmpty()) {
        vehicle_ = other.vehicle_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (other.getTotalSeats() != 0) {
        setTotalSeats(other.getTotalSeats());
      }
      if (other.getAdultPrice() != 0) {
        setAdultPrice(other.getAdultPrice());
      }
      if (other.getChildrenPrice() != 0) {
        setChildrenPrice(other.getChildrenPrice());
      }
      if (other.getBabyPrice() != 0) {
        setBabyPrice(other.getBabyPrice());
      }
      if (other.getTotalSubTours() != 0) {
        setTotalSubTours(other.getTotalSubTours());
      }
      if (!other.getCreatedTime().isEmpty()) {
        createdTime_ = other.createdTime_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              duration_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              departureLocation_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              vehicle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 48: {
              totalSeats_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              adultPrice_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              childrenPrice_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              babyPrice_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              totalSubTours_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              createdTime_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private int bitField0_;

    private int id_;

    /**
     * <code>int32 id = 1;</code>
     * 
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }

    /**
     * <code>int32 id = 1;</code>
     * 
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    /**
     * <code>int32 id = 1;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private Object title_ = "";

    /**
     * <code>string title = 2;</code>
     * 
     * @return The title.
     */
    public String getTitle() {
      Object ref = title_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string title = 2;</code>
     * 
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string title = 2;</code>
     * 
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    /**
     * <code>string title = 2;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    /**
     * <code>string title = 2;</code>
     * 
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private Object duration_ = "";

    /**
     * <code>string duration = 3;</code>
     * 
     * @return The duration.
     */
    public String getDuration() {
      Object ref = duration_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        duration_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string duration = 3;</code>
     * 
     * @return The bytes for duration.
     */
    public com.google.protobuf.ByteString getDurationBytes() {
      Object ref = duration_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (String) ref);
        duration_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string duration = 3;</code>
     * 
     * @param value The duration to set.
     * @return This builder for chaining.
     */
    public Builder setDuration(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      duration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    /**
     * <code>string duration = 3;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearDuration() {
      duration_ = getDefaultInstance().getDuration();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }

    /**
     * <code>string duration = 3;</code>
     * 
     * @param value The bytes for duration to set.
     * @return This builder for chaining.
     */
    public Builder setDurationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      duration_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private Object departureLocation_ = "";

    /**
     * <code>string departure_location = 4;</code>
     * 
     * @return The departureLocation.
     */
    public String getDepartureLocation() {
      Object ref = departureLocation_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        departureLocation_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string departure_location = 4;</code>
     * 
     * @return The bytes for departureLocation.
     */
    public com.google.protobuf.ByteString getDepartureLocationBytes() {
      Object ref = departureLocation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (String) ref);
        departureLocation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string departure_location = 4;</code>
     * 
     * @param value The departureLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLocation(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      departureLocation_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    /**
     * <code>string departure_location = 4;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearDepartureLocation() {
      departureLocation_ = getDefaultInstance().getDepartureLocation();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    /**
     * <code>string departure_location = 4;</code>
     * 
     * @param value The bytes for departureLocation to set.
     * @return This builder for chaining.
     */
    public Builder setDepartureLocationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      departureLocation_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private Object vehicle_ = "";

    /**
     * <code>string vehicle = 5;</code>
     * 
     * @return The vehicle.
     */
    public String getVehicle() {
      Object ref = vehicle_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        vehicle_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string vehicle = 5;</code>
     * 
     * @return The bytes for vehicle.
     */
    public com.google.protobuf.ByteString getVehicleBytes() {
      Object ref = vehicle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (String) ref);
        vehicle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string vehicle = 5;</code>
     * 
     * @param value The vehicle to set.
     * @return This builder for chaining.
     */
    public Builder setVehicle(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      vehicle_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    /**
     * <code>string vehicle = 5;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearVehicle() {
      vehicle_ = getDefaultInstance().getVehicle();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    /**
     * <code>string vehicle = 5;</code>
     * 
     * @param value The bytes for vehicle to set.
     * @return This builder for chaining.
     */
    public Builder setVehicleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      vehicle_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private int totalSeats_;

    /**
     * <code>int32 total_seats = 6;</code>
     * 
     * @return The totalSeats.
     */
    @Override
    public int getTotalSeats() {
      return totalSeats_;
    }

    /**
     * <code>int32 total_seats = 6;</code>
     * 
     * @param value The totalSeats to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSeats(int value) {

      totalSeats_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    /**
     * <code>int32 total_seats = 6;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTotalSeats() {
      bitField0_ = (bitField0_ & ~0x00000020);
      totalSeats_ = 0;
      onChanged();
      return this;
    }

    private int adultPrice_;

    /**
     * <code>int32 adult_price = 7;</code>
     * 
     * @return The adultPrice.
     */
    @Override
    public int getAdultPrice() {
      return adultPrice_;
    }

    /**
     * <code>int32 adult_price = 7;</code>
     * 
     * @param value The adultPrice to set.
     * @return This builder for chaining.
     */
    public Builder setAdultPrice(int value) {

      adultPrice_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    /**
     * <code>int32 adult_price = 7;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearAdultPrice() {
      bitField0_ = (bitField0_ & ~0x00000040);
      adultPrice_ = 0;
      onChanged();
      return this;
    }

    private int childrenPrice_;

    /**
     * <code>int32 children_price = 8;</code>
     * 
     * @return The childrenPrice.
     */
    @Override
    public int getChildrenPrice() {
      return childrenPrice_;
    }

    /**
     * <code>int32 children_price = 8;</code>
     * 
     * @param value The childrenPrice to set.
     * @return This builder for chaining.
     */
    public Builder setChildrenPrice(int value) {

      childrenPrice_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    /**
     * <code>int32 children_price = 8;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearChildrenPrice() {
      bitField0_ = (bitField0_ & ~0x00000080);
      childrenPrice_ = 0;
      onChanged();
      return this;
    }

    private int babyPrice_;

    /**
     * <code>int32 baby_price = 9;</code>
     * 
     * @return The babyPrice.
     */
    @Override
    public int getBabyPrice() {
      return babyPrice_;
    }

    /**
     * <code>int32 baby_price = 9;</code>
     * 
     * @param value The babyPrice to set.
     * @return This builder for chaining.
     */
    public Builder setBabyPrice(int value) {

      babyPrice_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    /**
     * <code>int32 baby_price = 9;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearBabyPrice() {
      bitField0_ = (bitField0_ & ~0x00000100);
      babyPrice_ = 0;
      onChanged();
      return this;
    }

    private int totalSubTours_;

    /**
     * <code>int32 total_sub_tours = 10;</code>
     * 
     * @return The totalSubTours.
     */
    @Override
    public int getTotalSubTours() {
      return totalSubTours_;
    }

    /**
     * <code>int32 total_sub_tours = 10;</code>
     * 
     * @param value The totalSubTours to set.
     * @return This builder for chaining.
     */
    public Builder setTotalSubTours(int value) {

      totalSubTours_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }

    /**
     * <code>int32 total_sub_tours = 10;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearTotalSubTours() {
      bitField0_ = (bitField0_ & ~0x00000200);
      totalSubTours_ = 0;
      onChanged();
      return this;
    }

    private Object createdTime_ = "";

    /**
     * <code>string created_time = 11;</code>
     * 
     * @return The createdTime.
     */
    public String getCreatedTime() {
      Object ref = createdTime_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        createdTime_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }

    /**
     * <code>string created_time = 11;</code>
     * 
     * @return The bytes for createdTime.
     */
    public com.google.protobuf.ByteString getCreatedTimeBytes() {
      Object ref = createdTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8(
            (String) ref);
        createdTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    /**
     * <code>string created_time = 11;</code>
     * 
     * @param value The createdTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedTime(
        String value) {
      if (value == null) {
        throw new NullPointerException();
      }
      createdTime_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    /**
     * <code>string created_time = 11;</code>
     * 
     * @return This builder for chaining.
     */
    public Builder clearCreatedTime() {
      createdTime_ = getDefaultInstance().getCreatedTime();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }

    /**
     * <code>string created_time = 11;</code>
     * 
     * @param value The bytes for createdTime to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
        throw new NullPointerException();
      }
      checkByteStringIsUtf8(value);
      createdTime_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

    // @@protoc_insertion_point(builder_scope:response.TourResponse)
  }

  // @@protoc_insertion_point(class_scope:response.TourResponse)
  private static final TourResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TourResponse();
  }

  public static TourResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TourResponse> PARSER = new com.google.protobuf.AbstractParser<TourResponse>() {
    @Override
    public TourResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TourResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TourResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public TourResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
