server:
  port: 8088
spring:
  application:
    name: mail-service
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/bk_travel_mail
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  mail:
    host: smtp.gmail.com
    port: 587
    username: gr1projectmailhust@gmail.com
    password: xutx mohn zokw nylp
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
eureka:
  instance:
    appname: mail-service
    # hostname: mail-service
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka
bk-travel:
  database:
    config:
      server:
        url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/bk_travel_mail
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
