// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staff/dto/response/check_staff_by_email_response.proto

// Protobuf Java Version: 3.25.1
package grpc.staff.dto.response;

/**
 * Protobuf type {@code response.CheckStaffByEmailResponse}
 */
public final class CheckStaffByEmailResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:response.CheckStaffByEmailResponse)
    CheckStaffByEmailResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckStaffByEmailResponse.newBuilder() to construct.
  private CheckStaffByEmailResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckStaffByEmailResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new CheckStaffByEmailResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return CheckStaffByEmailResponseOuterClass.internal_static_response_CheckStaffByEmailResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return CheckStaffByEmailResponseOuterClass.internal_static_response_CheckStaffByEmailResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            CheckStaffByEmailResponse.class, Builder.class);
  }

  private int bitField0_;
  public static final int IS_EXISTS_FIELD_NUMBER = 1;
  private boolean isExists_ = false;
  /**
   * <code>bool is_exists = 1;</code>
   * @return The isExists.
   */
  @Override
  public boolean getIsExists() {
    return isExists_;
  }

  public static final int STAFF_FIELD_NUMBER = 2;
  private StaffResponse staff_;
  /**
   * <code>.response.StaffResponse staff = 2;</code>
   * @return Whether the staff field is set.
   */
  @Override
  public boolean hasStaff() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.response.StaffResponse staff = 2;</code>
   * @return The staff.
   */
  @Override
  public StaffResponse getStaff() {
    return staff_ == null ? StaffResponse.getDefaultInstance() : staff_;
  }
  /**
   * <code>.response.StaffResponse staff = 2;</code>
   */
  @Override
  public StaffResponseOrBuilder getStaffOrBuilder() {
    return staff_ == null ? StaffResponse.getDefaultInstance() : staff_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isExists_ != false) {
      output.writeBool(1, isExists_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(2, getStaff());
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isExists_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isExists_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getStaff());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof CheckStaffByEmailResponse)) {
      return super.equals(obj);
    }
    CheckStaffByEmailResponse other = (CheckStaffByEmailResponse) obj;

    if (getIsExists()
        != other.getIsExists()) return false;
    if (hasStaff() != other.hasStaff()) return false;
    if (hasStaff()) {
      if (!getStaff()
          .equals(other.getStaff())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IS_EXISTS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsExists());
    if (hasStaff()) {
      hash = (37 * hash) + STAFF_FIELD_NUMBER;
      hash = (53 * hash) + getStaff().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static CheckStaffByEmailResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CheckStaffByEmailResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CheckStaffByEmailResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CheckStaffByEmailResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CheckStaffByEmailResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static CheckStaffByEmailResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static CheckStaffByEmailResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CheckStaffByEmailResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static CheckStaffByEmailResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static CheckStaffByEmailResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static CheckStaffByEmailResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static CheckStaffByEmailResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(CheckStaffByEmailResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code response.CheckStaffByEmailResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:response.CheckStaffByEmailResponse)
      CheckStaffByEmailResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return CheckStaffByEmailResponseOuterClass.internal_static_response_CheckStaffByEmailResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return CheckStaffByEmailResponseOuterClass.internal_static_response_CheckStaffByEmailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              CheckStaffByEmailResponse.class, Builder.class);
    }

    // Construct using grpc.staff.dto.response.CheckStaffByEmailResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStaffFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      isExists_ = false;
      staff_ = null;
      if (staffBuilder_ != null) {
        staffBuilder_.dispose();
        staffBuilder_ = null;
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return CheckStaffByEmailResponseOuterClass.internal_static_response_CheckStaffByEmailResponse_descriptor;
    }

    @Override
    public CheckStaffByEmailResponse getDefaultInstanceForType() {
      return CheckStaffByEmailResponse.getDefaultInstance();
    }

    @Override
    public CheckStaffByEmailResponse build() {
      CheckStaffByEmailResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public CheckStaffByEmailResponse buildPartial() {
      CheckStaffByEmailResponse result = new CheckStaffByEmailResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(CheckStaffByEmailResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.isExists_ = isExists_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.staff_ = staffBuilder_ == null
            ? staff_
            : staffBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof CheckStaffByEmailResponse) {
        return mergeFrom((CheckStaffByEmailResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(CheckStaffByEmailResponse other) {
      if (other == CheckStaffByEmailResponse.getDefaultInstance()) return this;
      if (other.getIsExists() != false) {
        setIsExists(other.getIsExists());
      }
      if (other.hasStaff()) {
        mergeStaff(other.getStaff());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              isExists_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              input.readMessage(
                  getStaffFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean isExists_ ;
    /**
     * <code>bool is_exists = 1;</code>
     * @return The isExists.
     */
    @Override
    public boolean getIsExists() {
      return isExists_;
    }
    /**
     * <code>bool is_exists = 1;</code>
     * @param value The isExists to set.
     * @return This builder for chaining.
     */
    public Builder setIsExists(boolean value) {

      isExists_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_exists = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsExists() {
      bitField0_ = (bitField0_ & ~0x00000001);
      isExists_ = false;
      onChanged();
      return this;
    }

    private StaffResponse staff_;
    private com.google.protobuf.SingleFieldBuilderV3<
        StaffResponse, StaffResponse.Builder, StaffResponseOrBuilder> staffBuilder_;
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     * @return Whether the staff field is set.
     */
    public boolean hasStaff() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     * @return The staff.
     */
    public StaffResponse getStaff() {
      if (staffBuilder_ == null) {
        return staff_ == null ? StaffResponse.getDefaultInstance() : staff_;
      } else {
        return staffBuilder_.getMessage();
      }
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    public Builder setStaff(StaffResponse value) {
      if (staffBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        staff_ = value;
      } else {
        staffBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    public Builder setStaff(
        StaffResponse.Builder builderForValue) {
      if (staffBuilder_ == null) {
        staff_ = builderForValue.build();
      } else {
        staffBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    public Builder mergeStaff(StaffResponse value) {
      if (staffBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          staff_ != null &&
          staff_ != StaffResponse.getDefaultInstance()) {
          getStaffBuilder().mergeFrom(value);
        } else {
          staff_ = value;
        }
      } else {
        staffBuilder_.mergeFrom(value);
      }
      if (staff_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    public Builder clearStaff() {
      bitField0_ = (bitField0_ & ~0x00000002);
      staff_ = null;
      if (staffBuilder_ != null) {
        staffBuilder_.dispose();
        staffBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    public StaffResponse.Builder getStaffBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getStaffFieldBuilder().getBuilder();
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    public StaffResponseOrBuilder getStaffOrBuilder() {
      if (staffBuilder_ != null) {
        return staffBuilder_.getMessageOrBuilder();
      } else {
        return staff_ == null ?
            StaffResponse.getDefaultInstance() : staff_;
      }
    }
    /**
     * <code>.response.StaffResponse staff = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        StaffResponse, StaffResponse.Builder, StaffResponseOrBuilder>
        getStaffFieldBuilder() {
      if (staffBuilder_ == null) {
        staffBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            StaffResponse, StaffResponse.Builder, StaffResponseOrBuilder>(
                getStaff(),
                getParentForChildren(),
                isClean());
        staff_ = null;
      }
      return staffBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:response.CheckStaffByEmailResponse)
  }

  // @@protoc_insertion_point(class_scope:response.CheckStaffByEmailResponse)
  private static final CheckStaffByEmailResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new CheckStaffByEmailResponse();
  }

  public static CheckStaffByEmailResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckStaffByEmailResponse>
      PARSER = new com.google.protobuf.AbstractParser<CheckStaffByEmailResponse>() {
    @Override
    public CheckStaffByEmailResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CheckStaffByEmailResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<CheckStaffByEmailResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public CheckStaffByEmailResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

