// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staff/dto/response/staff_response.proto

// Protobuf Java Version: 3.25.1
package grpc.staff.dto.response;

public interface StaffResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:response.StaffResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.fields.StaffIdField id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>.fields.StaffIdField id = 1;</code>
   * @return The id.
   */
  grpc.staff.fields.StaffIdField getId();
  /**
   * <code>.fields.StaffIdField id = 1;</code>
   */
  grpc.staff.fields.StaffIdFieldOrBuilder getIdOrBuilder();

  /**
   * <code>.fields.StaffEmailField email = 2;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>.fields.StaffEmailField email = 2;</code>
   * @return The email.
   */
  grpc.staff.fields.StaffEmailField getEmail();
  /**
   * <code>.fields.StaffEmailField email = 2;</code>
   */
  grpc.staff.fields.StaffEmailFieldOrBuilder getEmailOrBuilder();

  /**
   * <code>.fields.StaffFirstnameField firstname = 3;</code>
   * @return Whether the firstname field is set.
   */
  boolean hasFirstname();
  /**
   * <code>.fields.StaffFirstnameField firstname = 3;</code>
   * @return The firstname.
   */
  grpc.staff.fields.StaffFirstnameField getFirstname();
  /**
   * <code>.fields.StaffFirstnameField firstname = 3;</code>
   */
  grpc.staff.fields.StaffFirstnameFieldOrBuilder getFirstnameOrBuilder();

  /**
   * <code>.fields.StaffLastnameField lastname = 4;</code>
   * @return Whether the lastname field is set.
   */
  boolean hasLastname();
  /**
   * <code>.fields.StaffLastnameField lastname = 4;</code>
   * @return The lastname.
   */
  grpc.staff.fields.StaffLastnameField getLastname();
  /**
   * <code>.fields.StaffLastnameField lastname = 4;</code>
   */
  grpc.staff.fields.StaffLastnameFieldOrBuilder getLastnameOrBuilder();

  /**
   * <code>.constants.StaffGender gender = 5;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.constants.StaffGender gender = 5;</code>
   * @return The gender.
   */
  grpc.staff.constants.type.StaffGender getGender();

  /**
   * <code>.constants.StaffStatus status = 6;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.constants.StaffStatus status = 6;</code>
   * @return The status.
   */
  grpc.staff.constants.type.StaffStatus getStatus();

  /**
   * <code>.fields.StaffAvatarUrlField avatar_url = 7;</code>
   * @return Whether the avatarUrl field is set.
   */
  boolean hasAvatarUrl();
  /**
   * <code>.fields.StaffAvatarUrlField avatar_url = 7;</code>
   * @return The avatarUrl.
   */
  grpc.staff.fields.StaffAvatarUrlField getAvatarUrl();
  /**
   * <code>.fields.StaffAvatarUrlField avatar_url = 7;</code>
   */
  grpc.staff.fields.StaffAvatarUrlFieldOrBuilder getAvatarUrlOrBuilder();
}
