// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/services/account-getting.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.service;

public final class AccountGetting {
  private AccountGetting() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    String[] descriptorData = {
        "\n)account/v2/services/account-getting.pr" +
            "oto\022\007service\0326account/v2/dto/request/get" +
            "-account-by-id-request.proto\0329account/v2" +
            "/dto/request/get-account-by-email-reques" +
            "t.proto\032Iaccount/v2/dto/request/get-acco" +
            "unt-by-username-and-password-request.pro" +
            "to\032>account/v2/dto/request/get-profile-b" +
            "y-account-id-request.proto\0329account/v2/d" +
            "to/request/get-profile-by-email-request." +
            "proto\0328account/v2/dto/response/get-accou" +
            "nt-by-id-response.proto\032;account/v2/dto/" +
            "response/get-account-by-email-response.p" +
            "roto\032Kaccount/v2/dto/response/get-accoun" +
            "t-by-username-and-password-response.prot" +
            "o\032@account/v2/dto/response/get-profile-b" +
            "y-account-id-response.proto\032;account/v2/" +
            "dto/response/get-profile-by-email-respon" +
            "se.proto2\240\004\n\025AccountGettingService\022T\n\016Ge" +
            "tAccountById\022\036.request.GetAccountByIdReq" +
            "uest\032 .response.GetAccountByIdResponse\"\000" +
            "\022]\n\021GetAccountByEmail\022!.request.GetAccou" +
            "ntByEmailRequest\032#.response.GetAccountBy" +
            "EmailResponse\"\000\022\207\001\n\037GetAccountByUsername" +
            "AndPassword\022/.request.GetAccountByUserna" +
            "meAndPasswordRequest\0321.response.GetAccou" +
            "ntByUsernameAndPasswordResponse\"\000\022i\n\025Get" +
            "ProfileByAccountId\022%.request.GetProfileB" +
            "yAccountIdRequest\032\'.response.GetProfileB" +
            "yAccountIdResponse\"\000\022]\n\021GetProfileByEmai" +
            "l\022!.request.GetProfileByEmailRequest\032#.r" +
            "esponse.GetProfileByEmailResponse\"\000B\033\n\027g" +
            "rpc.account.v2.serviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
                grpc.account.v2.dto.request.GetAccountByIdRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.request.GetAccountByEmailRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.request.GetAccountByUsernameAndPasswordRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.request.GetProfileByAccountIdRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.request.GetProfileByEmailRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.GetAccountByIdResponseOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.GetAccountByEmailResponseOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.GetAccountByUsernameAndPasswordResponseOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.GetProfileByEmailResponseOuterClass.getDescriptor(),
            });
    grpc.account.v2.dto.request.GetAccountByIdRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.request.GetAccountByEmailRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.request.GetAccountByUsernameAndPasswordRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.request.GetProfileByAccountIdRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.request.GetProfileByEmailRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.response.GetAccountByIdResponseOuterClass.getDescriptor();
    grpc.account.v2.dto.response.GetAccountByEmailResponseOuterClass.getDescriptor();
    grpc.account.v2.dto.response.GetAccountByUsernameAndPasswordResponseOuterClass.getDescriptor();
    grpc.account.v2.dto.response.GetProfileByAccountIdResponseOuterClass.getDescriptor();
    grpc.account.v2.dto.response.GetProfileByEmailResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
