// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/services/account-creating.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.service;

public final class AccountCreating {
  private AccountCreating() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    String[] descriptorData = {
        "\n*account/v2/services/account-creating.p" +
            "roto\022\007service\0323account/v2/dto/request/cr" +
            "eate-account-request.proto\0323account/v2/d" +
            "to/request/create-profile-request.proto\032" +
            "5account/v2/dto/response/create-account-" +
            "response.proto\0325account/v2/dto/response/" +
            "create-profile-response.proto2\276\001\n\026Accoun" +
            "tCreatingService\022Q\n\rCreateAccount\022\035.requ" +
            "est.CreateAccountRequest\032\037.response.Crea" +
            "teAccountResponse\"\000\022Q\n\rCreateProfile\022\035.r" +
            "equest.CreateProfileRequest\032\037.response.C" +
            "reateProfileResponse\"\000B\033\n\027grpc.account.v" +
            "2.serviceP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
                grpc.account.v2.dto.request.CreateAccountRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.request.CreateProfileRequestOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.CreateAccountResponseOuterClass.getDescriptor(),
                grpc.account.v2.dto.response.CreateProfileResponseOuterClass.getDescriptor(),
            });
    grpc.account.v2.dto.request.CreateAccountRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.request.CreateProfileRequestOuterClass.getDescriptor();
    grpc.account.v2.dto.response.CreateAccountResponseOuterClass.getDescriptor();
    grpc.account.v2.dto.response.CreateProfileResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
