server:
  port: 8080
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
eureka:
  server:
    host: discovery-server
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:8761/eureka
