// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tour/fields/subtour-id-field.proto

// Protobuf Java Version: 3.25.1
package grpc.tour.fields;

public interface SubTourIdFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fields.SubTourIdField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 value = 1;</code>
   * 
   * @return The value.
   */
  int getValue();
}
