// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: payment/constants/type.proto

// Protobuf Java Version: 3.25.1
package grpc.payment.type;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034payment/constants/type.proto\022\tconstant" +
      "s*6\n\rPaymentStatus\022\013\n\007SUCCESS\020\000\022\n\n\006FAILE" +
      "D\020\001\022\014\n\010CANCELED\020\002B\025\n\021grpc.payment.typeP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
