// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/request/check-account-by-email-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.request;

public interface CheckAccountByEmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request.CheckAccountByEmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * 
   * @return The email.
   */
  String getEmail();

  /**
   * <code>string email = 1;</code>
   * 
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString getEmailBytes();
}
