// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/dto/request/check-account-by-email-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.dto.request;

public final class CheckAccountByEmailRequestOuterClass {
  private CheckAccountByEmailRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_request_CheckAccountByEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_request_CheckAccountByEmailRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n8account/dto/request/check-account-by-e" +
      "mail-request.proto\022\007request\032(account/fie" +
      "lds/account-email-field.proto\"N\n\032CheckAc" +
      "countByEmailRequest\0220\n\raccount_email\030\001 \001" +
      "(\0132\031.fields.AccountEmailFieldB\034\n\030grpc.ac" +
      "count.dto.requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.account.fields.AccountEmailFieldOuterClass.getDescriptor(),
        });
    internal_static_request_CheckAccountByEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_request_CheckAccountByEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_CheckAccountByEmailRequest_descriptor,
        new String[] { "AccountEmail", });
    grpc.account.fields.AccountEmailFieldOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
