// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking/constants/type.proto

// Protobuf Java Version: 3.25.1
package grpc.booking.constants;

public final class Type {
  private Type() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\034booking/constants/type.proto\022\tconstant" +
      "s*t\n\rPaymentMethod\022\t\n\005VNPAY\020\000\022\017\n\013VIETTEL" +
      "_PAY\020\001\022\014\n\010ZALO_PAY\020\002\022\014\n\010MOMO_PAY\020\003\022\n\n\006PA" +
      "YPAL\020\004\022\017\n\013CREDIT_CARD\020\005\022\016\n\nDEBIT_CARD\020\006B" +
      "\032\n\026grpc.booking.constantsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
