// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/dto/request/check-profile-by-account-id-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.dto.request;

public interface CheckProfileByAccountIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request.CheckProfileByAccountIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.fields.AccountIdField account_id = 1;</code>
   * 
   * @return Whether the accountId field is set.
   */
  boolean hasAccountId();

  /**
   * <code>.fields.AccountIdField account_id = 1;</code>
   * 
   * @return The accountId.
   */
  grpc.account.fields.AccountIdField getAccountId();

  /**
   * <code>.fields.AccountIdField account_id = 1;</code>
   */
  grpc.account.fields.AccountIdFieldOrBuilder getAccountIdOrBuilder();
}
