// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/dto/request/check-account-by-email-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.dto.request;

public interface CheckAccountByEmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request.CheckAccountByEmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.fields.AccountEmailField account_email = 1;</code>
   * @return Whether the accountEmail field is set.
   */
  boolean hasAccountEmail();
  /**
   * <code>.fields.AccountEmailField account_email = 1;</code>
   * @return The accountEmail.
   */
  grpc.account.fields.AccountEmailField getAccountEmail();
  /**
   * <code>.fields.AccountEmailField account_email = 1;</code>
   */
  grpc.account.fields.AccountEmailFieldOrBuilder getAccountEmailOrBuilder();
}
