// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking/v2/dto/response/check-booking-by-id-response.proto

// Protobuf Java Version: 3.25.1
package grpc.booking.v2.dto.response;

public final class CheckBookingByIdResponseOuterClass {
  private CheckBookingByIdResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_response_CheckBookingByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_response_CheckBookingByIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n:booking/v2/dto/response/check-booking-" +
      "by-id-response.proto\022\010response\032\036booking/" +
      "v2/model/booking.proto\"-\n\030CheckBookingBy" +
      "IdResponse\022\021\n\tis_exists\030\001 \001(\010B \n\034grpc.bo" +
      "oking.v2.dto.responseP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.booking.v2.model.BookingOuterClass.getDescriptor(),
        });
    internal_static_response_CheckBookingByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_response_CheckBookingByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_response_CheckBookingByIdResponse_descriptor,
        new String[] { "IsExists", });
    grpc.booking.v2.model.BookingOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
