// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

// Protobuf Java Version: 3.25.1
package grpc.account;

public interface ExistAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ExistAccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool value = 1;</code>
   * @return The value.
   */
  boolean getValue();
}
