// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/request/check-account-by-id-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.request;

public final class CheckAccountByIdRequestOuterClass {
  private CheckAccountByIdRequestOuterClass() {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor internal_static_request_CheckAccountByIdRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_request_CheckAccountByIdRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
  static {
    java.lang.String[] descriptorData = {
        "\n8account/v2/dto/request/check-account-b" +
            "y-id-request.proto\022\007request\"-\n\027CheckAcco" +
            "untByIdRequest\022\022\n\naccount_id\030\001 \001(\005B\037\n\033gr" +
            "pc.account.v2.dto.requestP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            });
    internal_static_request_CheckAccountByIdRequest_descriptor = getDescriptor().getMessageTypes().get(0);
    internal_static_request_CheckAccountByIdRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_request_CheckAccountByIdRequest_descriptor,
        new java.lang.String[] { "AccountId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
