// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/request/create-account-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.request;

public interface CreateAccountRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:request.CreateAccountRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     * 
     * @return The username.
     */
    java.lang.String getUsername();

    /**
     * <code>string username = 1;</code>
     * 
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString getUsernameBytes();

    /**
     * <code>string email = 2;</code>
     * 
     * @return The email.
     */
    java.lang.String getEmail();

    /**
     * <code>string email = 2;</code>
     * 
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString getEmailBytes();

    /**
     * <code>string password = 3;</code>
     * 
     * @return The password.
     */
    java.lang.String getPassword();

    /**
     * <code>string password = 3;</code>
     * 
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString getPasswordBytes();
}
