server:
  port: 8082
spring:
  application:
    name: account-service
  data:
    web:
      pageable:
        one-indexed-parameters: true
        size-parameter: size
        page-parameter: page
      sort:
        sort-parameter: sort
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bk_travel_account}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  liquibase:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bk_travel_account}
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  instance:
    # hostname: account-service
    appname: account-service
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka
mysql-server:
  hostname: mysql-server
  user: root
  password: root
  port: 3306
grpc:
  server:
    port: 50082
