// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/fields/account-email-field.proto

// Protobuf Java Version: 3.25.1
package grpc.account.fields;

public interface AccountEmailFieldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:fields.AccountEmailField)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
