// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/request/get-account-by-id-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.request;

public interface GetAccountByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:request.GetAccountByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 account_id = 1;</code>
   * 
   * @return The accountId.
   */
  int getAccountId();
}
