// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account/v2/dto/request/get-account-by-username-and-password-request.proto

// Protobuf Java Version: 3.25.1
package grpc.account.v2.dto.request;

public interface GetAccountByUsernameAndPasswordRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:request.GetAccountByUsernameAndPasswordRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 1;</code>
     * 
     * @return The username.
     */
    java.lang.String getUsername();

    /**
     * <code>string username = 1;</code>
     * 
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString getUsernameBytes();

    /**
     * <code>string password = 2;</code>
     * 
     * @return The password.
     */
    java.lang.String getPassword();

    /**
     * <code>string password = 2;</code>
     * 
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString getPasswordBytes();
}
