server:
  port: 8083
spring:
  application:
    name: tour-service
  datasource:
    url: jdbc:mysql://mysql-server:3306/bk_travel_tour
    username: root
    password: root
  liquibase:
    url: jdbc:mysql://mysql-server:3306/bk_travel_tour
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL8Dialect
      "[hibernate.format_sql]": true
# logging:
#   level:
#     "[org.hibernate.SQL]": DEBUG
#     "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
# ---------------
# Euraka config
# ---------------
eureka:
  instance:
    hostname: localhost
  server:
    host: discovery-server
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.server.host}:${eureka.server.port}/eureka
# ---------------
# Euraka config
# ---------------
bk-travel:
  config:
    database:
      server:
        url: r2dbc:mysql://mysql-server:3306/bk_travel_tour
        username: root
        password: root
