server:
  port: 8083
spring:
  application:
    name: tour-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bk_travel_tour}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
  liquibase:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bk_travel_tour}
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.MySQL8Dialect
      "[hibernate.format_sql]": true
# logging:
#   level:
#     "[org.hibernate.SQL]": DEBUG
#     "[org.hibernate.type.descriptor.sql.BasicBinder]": TRACE
# ---------------
# Eureka config
# ---------------
eureka:
  instance:
    appname: tour-service
#    hostname: ${SERVICE_INSTANCE_HOST:localhost}
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka
# ---------------
# gRPC config
# ---------------
grpc:
  server:
    port: 50083
cloudinary:
  cloud-name: dtm4bscge
  api-key: 753338592148366
  api-secret: 9DuFjid4CY301yghd9iA1tEdyjo
  secure: true
# ---------------
# Kafka config
# ---------------
kafka:
  bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:${KAFKA_BROKER_PORT:9092}
  consumer:
    group-id: tour-service-group
    auto-offset-reset: latest
