server:
  port: 8091
spring:
  application:
    name: marking-service
  liquibase:
    url: jdbc:mysql://mysql-server:3306/bk_travel_marking
    user: root
    password: root
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  instance:
    hostname: localhost
    appname: marking-service
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka
bk-travel:
  database:
    config:
      server:
        url: r2dbc:mysql://mysql-server:3306/bk_travel_marking
        username: root
        password: root
