// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

// Protobuf Java Version: 3.25.1
package com.aresky.accountservice.grpc.account;

public interface AccountIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AccountIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
