// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: account-service.proto

// Protobuf Java Version: 3.25.1
package com.aresky.accountservice.grpc.account;

public interface CreateAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateAccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
