// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: staff/fields/staff_firstname_field.proto

// Protobuf Java Version: 3.25.1
package grpc.staff.fields;

public final class StaffFirstnameFieldOuterClass {
  private StaffFirstnameFieldOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fields_StaffFirstnameField_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_fields_StaffFirstnameField_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n(staff/fields/staff_firstname_field.pro" +
      "to\022\006fields\"(\n\023StaffFirstnameField\022\021\n\tfis" +
      "t_name\030\001 \001(\tB\025\n\021grpc.staff.fieldsP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_fields_StaffFirstnameField_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_fields_StaffFirstnameField_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_fields_StaffFirstnameField_descriptor,
        new String[] { "FistName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
