server:
  port: 8089
spring:
  application:
    name: review-service
eureka:
  instance:
    hostname: localhost
    appname: review-service
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
bk-travel:
  database:
    config:
      server:
        url: r2dbc:mysql://localhost:3306/bk_travel_review
        username: root
        password: root
