server:
  port: 8089
spring:
  application:
    name: review-service
  liquibase:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/bk_travel_review
    user: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
    change-log: classpath:db/changelog/changelog-master.xml
eureka:
  instance:
    # hostname: review-service
    appname: review-service
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_HOST:localhost}:${SERVICE_REGISTRY_PORT:8761}/eureka
bk-travel:
  database:
    config:
      server:
        url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/bk_travel_review
        username: ${DB_USER:root}
        password: ${DB_PASSWORD:root}
